# AUTO-GENERATED by split_ctp_wrapper.py — DO NOT EDIT
"""CTP 行情/合约/产品/交易所相关结构"""

from __future__ import annotations

from ._ctp_base import _ctp, _swig_repr


class CThostFtdcDisseminationField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    SequenceSeries = property(
        _ctp.CThostFtdcDisseminationField_SequenceSeries_get,
        _ctp.CThostFtdcDisseminationField_SequenceSeries_set,
    )
    SequenceNo = property(
        _ctp.CThostFtdcDisseminationField_SequenceNo_get,
        _ctp.CThostFtdcDisseminationField_SequenceNo_set,
    )

    def __init__(self):
        _ctp.CThostFtdcDisseminationField_swiginit(self, _ctp.new_CThostFtdcDisseminationField())

    __swig_destroy__ = _ctp.delete_CThostFtdcDisseminationField


# Register CThostFtdcDisseminationField in _ctp:
_ctp.CThostFtdcDisseminationField_swigregister(CThostFtdcDisseminationField)


class CThostFtdcExchangeField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    ExchangeID = property(
        _ctp.CThostFtdcExchangeField_ExchangeID_get, _ctp.CThostFtdcExchangeField_ExchangeID_set
    )
    ExchangeName = property(
        _ctp.CThostFtdcExchangeField_ExchangeName_get, _ctp.CThostFtdcExchangeField_ExchangeName_set
    )
    ExchangeProperty = property(
        _ctp.CThostFtdcExchangeField_ExchangeProperty_get,
        _ctp.CThostFtdcExchangeField_ExchangeProperty_set,
    )

    def __init__(self):
        _ctp.CThostFtdcExchangeField_swiginit(self, _ctp.new_CThostFtdcExchangeField())

    __swig_destroy__ = _ctp.delete_CThostFtdcExchangeField


# Register CThostFtdcExchangeField in _ctp:
_ctp.CThostFtdcExchangeField_swigregister(CThostFtdcExchangeField)


class CThostFtdcProductField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    reserve1 = property(
        _ctp.CThostFtdcProductField_reserve1_get, _ctp.CThostFtdcProductField_reserve1_set
    )
    ProductName = property(
        _ctp.CThostFtdcProductField_ProductName_get, _ctp.CThostFtdcProductField_ProductName_set
    )
    ExchangeID = property(
        _ctp.CThostFtdcProductField_ExchangeID_get, _ctp.CThostFtdcProductField_ExchangeID_set
    )
    ProductClass = property(
        _ctp.CThostFtdcProductField_ProductClass_get, _ctp.CThostFtdcProductField_ProductClass_set
    )
    VolumeMultiple = property(
        _ctp.CThostFtdcProductField_VolumeMultiple_get,
        _ctp.CThostFtdcProductField_VolumeMultiple_set,
    )
    PriceTick = property(
        _ctp.CThostFtdcProductField_PriceTick_get, _ctp.CThostFtdcProductField_PriceTick_set
    )
    MaxMarketOrderVolume = property(
        _ctp.CThostFtdcProductField_MaxMarketOrderVolume_get,
        _ctp.CThostFtdcProductField_MaxMarketOrderVolume_set,
    )
    MinMarketOrderVolume = property(
        _ctp.CThostFtdcProductField_MinMarketOrderVolume_get,
        _ctp.CThostFtdcProductField_MinMarketOrderVolume_set,
    )
    MaxLimitOrderVolume = property(
        _ctp.CThostFtdcProductField_MaxLimitOrderVolume_get,
        _ctp.CThostFtdcProductField_MaxLimitOrderVolume_set,
    )
    MinLimitOrderVolume = property(
        _ctp.CThostFtdcProductField_MinLimitOrderVolume_get,
        _ctp.CThostFtdcProductField_MinLimitOrderVolume_set,
    )
    PositionType = property(
        _ctp.CThostFtdcProductField_PositionType_get, _ctp.CThostFtdcProductField_PositionType_set
    )
    PositionDateType = property(
        _ctp.CThostFtdcProductField_PositionDateType_get,
        _ctp.CThostFtdcProductField_PositionDateType_set,
    )
    CloseDealType = property(
        _ctp.CThostFtdcProductField_CloseDealType_get, _ctp.CThostFtdcProductField_CloseDealType_set
    )
    TradeCurrencyID = property(
        _ctp.CThostFtdcProductField_TradeCurrencyID_get,
        _ctp.CThostFtdcProductField_TradeCurrencyID_set,
    )
    MortgageFundUseRange = property(
        _ctp.CThostFtdcProductField_MortgageFundUseRange_get,
        _ctp.CThostFtdcProductField_MortgageFundUseRange_set,
    )
    reserve2 = property(
        _ctp.CThostFtdcProductField_reserve2_get, _ctp.CThostFtdcProductField_reserve2_set
    )
    UnderlyingMultiple = property(
        _ctp.CThostFtdcProductField_UnderlyingMultiple_get,
        _ctp.CThostFtdcProductField_UnderlyingMultiple_set,
    )
    ProductID = property(
        _ctp.CThostFtdcProductField_ProductID_get, _ctp.CThostFtdcProductField_ProductID_set
    )
    ExchangeProductID = property(
        _ctp.CThostFtdcProductField_ExchangeProductID_get,
        _ctp.CThostFtdcProductField_ExchangeProductID_set,
    )
    OpenLimitControlLevel = property(
        _ctp.CThostFtdcProductField_OpenLimitControlLevel_get,
        _ctp.CThostFtdcProductField_OpenLimitControlLevel_set,
    )
    OrderFreqControlLevel = property(
        _ctp.CThostFtdcProductField_OrderFreqControlLevel_get,
        _ctp.CThostFtdcProductField_OrderFreqControlLevel_set,
    )

    def __init__(self):
        _ctp.CThostFtdcProductField_swiginit(self, _ctp.new_CThostFtdcProductField())

    __swig_destroy__ = _ctp.delete_CThostFtdcProductField


# Register CThostFtdcProductField in _ctp:
_ctp.CThostFtdcProductField_swigregister(CThostFtdcProductField)


class CThostFtdcInstrumentField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    reserve1 = property(
        _ctp.CThostFtdcInstrumentField_reserve1_get, _ctp.CThostFtdcInstrumentField_reserve1_set
    )
    ExchangeID = property(
        _ctp.CThostFtdcInstrumentField_ExchangeID_get, _ctp.CThostFtdcInstrumentField_ExchangeID_set
    )
    InstrumentName = property(
        _ctp.CThostFtdcInstrumentField_InstrumentName_get,
        _ctp.CThostFtdcInstrumentField_InstrumentName_set,
    )
    reserve2 = property(
        _ctp.CThostFtdcInstrumentField_reserve2_get, _ctp.CThostFtdcInstrumentField_reserve2_set
    )
    reserve3 = property(
        _ctp.CThostFtdcInstrumentField_reserve3_get, _ctp.CThostFtdcInstrumentField_reserve3_set
    )
    ProductClass = property(
        _ctp.CThostFtdcInstrumentField_ProductClass_get,
        _ctp.CThostFtdcInstrumentField_ProductClass_set,
    )
    DeliveryYear = property(
        _ctp.CThostFtdcInstrumentField_DeliveryYear_get,
        _ctp.CThostFtdcInstrumentField_DeliveryYear_set,
    )
    DeliveryMonth = property(
        _ctp.CThostFtdcInstrumentField_DeliveryMonth_get,
        _ctp.CThostFtdcInstrumentField_DeliveryMonth_set,
    )
    MaxMarketOrderVolume = property(
        _ctp.CThostFtdcInstrumentField_MaxMarketOrderVolume_get,
        _ctp.CThostFtdcInstrumentField_MaxMarketOrderVolume_set,
    )
    MinMarketOrderVolume = property(
        _ctp.CThostFtdcInstrumentField_MinMarketOrderVolume_get,
        _ctp.CThostFtdcInstrumentField_MinMarketOrderVolume_set,
    )
    MaxLimitOrderVolume = property(
        _ctp.CThostFtdcInstrumentField_MaxLimitOrderVolume_get,
        _ctp.CThostFtdcInstrumentField_MaxLimitOrderVolume_set,
    )
    MinLimitOrderVolume = property(
        _ctp.CThostFtdcInstrumentField_MinLimitOrderVolume_get,
        _ctp.CThostFtdcInstrumentField_MinLimitOrderVolume_set,
    )
    VolumeMultiple = property(
        _ctp.CThostFtdcInstrumentField_VolumeMultiple_get,
        _ctp.CThostFtdcInstrumentField_VolumeMultiple_set,
    )
    PriceTick = property(
        _ctp.CThostFtdcInstrumentField_PriceTick_get, _ctp.CThostFtdcInstrumentField_PriceTick_set
    )
    CreateDate = property(
        _ctp.CThostFtdcInstrumentField_CreateDate_get, _ctp.CThostFtdcInstrumentField_CreateDate_set
    )
    OpenDate = property(
        _ctp.CThostFtdcInstrumentField_OpenDate_get, _ctp.CThostFtdcInstrumentField_OpenDate_set
    )
    ExpireDate = property(
        _ctp.CThostFtdcInstrumentField_ExpireDate_get, _ctp.CThostFtdcInstrumentField_ExpireDate_set
    )
    StartDelivDate = property(
        _ctp.CThostFtdcInstrumentField_StartDelivDate_get,
        _ctp.CThostFtdcInstrumentField_StartDelivDate_set,
    )
    EndDelivDate = property(
        _ctp.CThostFtdcInstrumentField_EndDelivDate_get,
        _ctp.CThostFtdcInstrumentField_EndDelivDate_set,
    )
    InstLifePhase = property(
        _ctp.CThostFtdcInstrumentField_InstLifePhase_get,
        _ctp.CThostFtdcInstrumentField_InstLifePhase_set,
    )
    IsTrading = property(
        _ctp.CThostFtdcInstrumentField_IsTrading_get, _ctp.CThostFtdcInstrumentField_IsTrading_set
    )
    PositionType = property(
        _ctp.CThostFtdcInstrumentField_PositionType_get,
        _ctp.CThostFtdcInstrumentField_PositionType_set,
    )
    PositionDateType = property(
        _ctp.CThostFtdcInstrumentField_PositionDateType_get,
        _ctp.CThostFtdcInstrumentField_PositionDateType_set,
    )
    LongMarginRatio = property(
        _ctp.CThostFtdcInstrumentField_LongMarginRatio_get,
        _ctp.CThostFtdcInstrumentField_LongMarginRatio_set,
    )
    ShortMarginRatio = property(
        _ctp.CThostFtdcInstrumentField_ShortMarginRatio_get,
        _ctp.CThostFtdcInstrumentField_ShortMarginRatio_set,
    )
    MaxMarginSideAlgorithm = property(
        _ctp.CThostFtdcInstrumentField_MaxMarginSideAlgorithm_get,
        _ctp.CThostFtdcInstrumentField_MaxMarginSideAlgorithm_set,
    )
    reserve4 = property(
        _ctp.CThostFtdcInstrumentField_reserve4_get, _ctp.CThostFtdcInstrumentField_reserve4_set
    )
    StrikePrice = property(
        _ctp.CThostFtdcInstrumentField_StrikePrice_get,
        _ctp.CThostFtdcInstrumentField_StrikePrice_set,
    )
    OptionsType = property(
        _ctp.CThostFtdcInstrumentField_OptionsType_get,
        _ctp.CThostFtdcInstrumentField_OptionsType_set,
    )
    UnderlyingMultiple = property(
        _ctp.CThostFtdcInstrumentField_UnderlyingMultiple_get,
        _ctp.CThostFtdcInstrumentField_UnderlyingMultiple_set,
    )
    CombinationType = property(
        _ctp.CThostFtdcInstrumentField_CombinationType_get,
        _ctp.CThostFtdcInstrumentField_CombinationType_set,
    )
    InstrumentID = property(
        _ctp.CThostFtdcInstrumentField_InstrumentID_get,
        _ctp.CThostFtdcInstrumentField_InstrumentID_set,
    )
    ExchangeInstID = property(
        _ctp.CThostFtdcInstrumentField_ExchangeInstID_get,
        _ctp.CThostFtdcInstrumentField_ExchangeInstID_set,
    )
    ProductID = property(
        _ctp.CThostFtdcInstrumentField_ProductID_get, _ctp.CThostFtdcInstrumentField_ProductID_set
    )
    UnderlyingInstrID = property(
        _ctp.CThostFtdcInstrumentField_UnderlyingInstrID_get,
        _ctp.CThostFtdcInstrumentField_UnderlyingInstrID_set,
    )

    def __init__(self):
        _ctp.CThostFtdcInstrumentField_swiginit(self, _ctp.new_CThostFtdcInstrumentField())

    __swig_destroy__ = _ctp.delete_CThostFtdcInstrumentField


# Register CThostFtdcInstrumentField in _ctp:
_ctp.CThostFtdcInstrumentField_swigregister(CThostFtdcInstrumentField)


class CThostFtdcDepthMarketDataField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    TradingDay = property(
        _ctp.CThostFtdcDepthMarketDataField_TradingDay_get,
        _ctp.CThostFtdcDepthMarketDataField_TradingDay_set,
    )
    reserve1 = property(
        _ctp.CThostFtdcDepthMarketDataField_reserve1_get,
        _ctp.CThostFtdcDepthMarketDataField_reserve1_set,
    )
    ExchangeID = property(
        _ctp.CThostFtdcDepthMarketDataField_ExchangeID_get,
        _ctp.CThostFtdcDepthMarketDataField_ExchangeID_set,
    )
    reserve2 = property(
        _ctp.CThostFtdcDepthMarketDataField_reserve2_get,
        _ctp.CThostFtdcDepthMarketDataField_reserve2_set,
    )
    LastPrice = property(
        _ctp.CThostFtdcDepthMarketDataField_LastPrice_get,
        _ctp.CThostFtdcDepthMarketDataField_LastPrice_set,
    )
    PreSettlementPrice = property(
        _ctp.CThostFtdcDepthMarketDataField_PreSettlementPrice_get,
        _ctp.CThostFtdcDepthMarketDataField_PreSettlementPrice_set,
    )
    PreClosePrice = property(
        _ctp.CThostFtdcDepthMarketDataField_PreClosePrice_get,
        _ctp.CThostFtdcDepthMarketDataField_PreClosePrice_set,
    )
    PreOpenInterest = property(
        _ctp.CThostFtdcDepthMarketDataField_PreOpenInterest_get,
        _ctp.CThostFtdcDepthMarketDataField_PreOpenInterest_set,
    )
    OpenPrice = property(
        _ctp.CThostFtdcDepthMarketDataField_OpenPrice_get,
        _ctp.CThostFtdcDepthMarketDataField_OpenPrice_set,
    )
    HighestPrice = property(
        _ctp.CThostFtdcDepthMarketDataField_HighestPrice_get,
        _ctp.CThostFtdcDepthMarketDataField_HighestPrice_set,
    )
    LowestPrice = property(
        _ctp.CThostFtdcDepthMarketDataField_LowestPrice_get,
        _ctp.CThostFtdcDepthMarketDataField_LowestPrice_set,
    )
    Volume = property(
        _ctp.CThostFtdcDepthMarketDataField_Volume_get,
        _ctp.CThostFtdcDepthMarketDataField_Volume_set,
    )
    Turnover = property(
        _ctp.CThostFtdcDepthMarketDataField_Turnover_get,
        _ctp.CThostFtdcDepthMarketDataField_Turnover_set,
    )
    OpenInterest = property(
        _ctp.CThostFtdcDepthMarketDataField_OpenInterest_get,
        _ctp.CThostFtdcDepthMarketDataField_OpenInterest_set,
    )
    ClosePrice = property(
        _ctp.CThostFtdcDepthMarketDataField_ClosePrice_get,
        _ctp.CThostFtdcDepthMarketDataField_ClosePrice_set,
    )
    SettlementPrice = property(
        _ctp.CThostFtdcDepthMarketDataField_SettlementPrice_get,
        _ctp.CThostFtdcDepthMarketDataField_SettlementPrice_set,
    )
    UpperLimitPrice = property(
        _ctp.CThostFtdcDepthMarketDataField_UpperLimitPrice_get,
        _ctp.CThostFtdcDepthMarketDataField_UpperLimitPrice_set,
    )
    LowerLimitPrice = property(
        _ctp.CThostFtdcDepthMarketDataField_LowerLimitPrice_get,
        _ctp.CThostFtdcDepthMarketDataField_LowerLimitPrice_set,
    )
    PreDelta = property(
        _ctp.CThostFtdcDepthMarketDataField_PreDelta_get,
        _ctp.CThostFtdcDepthMarketDataField_PreDelta_set,
    )
    CurrDelta = property(
        _ctp.CThostFtdcDepthMarketDataField_CurrDelta_get,
        _ctp.CThostFtdcDepthMarketDataField_CurrDelta_set,
    )
    UpdateTime = property(
        _ctp.CThostFtdcDepthMarketDataField_UpdateTime_get,
        _ctp.CThostFtdcDepthMarketDataField_UpdateTime_set,
    )
    UpdateMillisec = property(
        _ctp.CThostFtdcDepthMarketDataField_UpdateMillisec_get,
        _ctp.CThostFtdcDepthMarketDataField_UpdateMillisec_set,
    )
    BidPrice1 = property(
        _ctp.CThostFtdcDepthMarketDataField_BidPrice1_get,
        _ctp.CThostFtdcDepthMarketDataField_BidPrice1_set,
    )
    BidVolume1 = property(
        _ctp.CThostFtdcDepthMarketDataField_BidVolume1_get,
        _ctp.CThostFtdcDepthMarketDataField_BidVolume1_set,
    )
    AskPrice1 = property(
        _ctp.CThostFtdcDepthMarketDataField_AskPrice1_get,
        _ctp.CThostFtdcDepthMarketDataField_AskPrice1_set,
    )
    AskVolume1 = property(
        _ctp.CThostFtdcDepthMarketDataField_AskVolume1_get,
        _ctp.CThostFtdcDepthMarketDataField_AskVolume1_set,
    )
    BidPrice2 = property(
        _ctp.CThostFtdcDepthMarketDataField_BidPrice2_get,
        _ctp.CThostFtdcDepthMarketDataField_BidPrice2_set,
    )
    BidVolume2 = property(
        _ctp.CThostFtdcDepthMarketDataField_BidVolume2_get,
        _ctp.CThostFtdcDepthMarketDataField_BidVolume2_set,
    )
    AskPrice2 = property(
        _ctp.CThostFtdcDepthMarketDataField_AskPrice2_get,
        _ctp.CThostFtdcDepthMarketDataField_AskPrice2_set,
    )
    AskVolume2 = property(
        _ctp.CThostFtdcDepthMarketDataField_AskVolume2_get,
        _ctp.CThostFtdcDepthMarketDataField_AskVolume2_set,
    )
    BidPrice3 = property(
        _ctp.CThostFtdcDepthMarketDataField_BidPrice3_get,
        _ctp.CThostFtdcDepthMarketDataField_BidPrice3_set,
    )
    BidVolume3 = property(
        _ctp.CThostFtdcDepthMarketDataField_BidVolume3_get,
        _ctp.CThostFtdcDepthMarketDataField_BidVolume3_set,
    )
    AskPrice3 = property(
        _ctp.CThostFtdcDepthMarketDataField_AskPrice3_get,
        _ctp.CThostFtdcDepthMarketDataField_AskPrice3_set,
    )
    AskVolume3 = property(
        _ctp.CThostFtdcDepthMarketDataField_AskVolume3_get,
        _ctp.CThostFtdcDepthMarketDataField_AskVolume3_set,
    )
    BidPrice4 = property(
        _ctp.CThostFtdcDepthMarketDataField_BidPrice4_get,
        _ctp.CThostFtdcDepthMarketDataField_BidPrice4_set,
    )
    BidVolume4 = property(
        _ctp.CThostFtdcDepthMarketDataField_BidVolume4_get,
        _ctp.CThostFtdcDepthMarketDataField_BidVolume4_set,
    )
    AskPrice4 = property(
        _ctp.CThostFtdcDepthMarketDataField_AskPrice4_get,
        _ctp.CThostFtdcDepthMarketDataField_AskPrice4_set,
    )
    AskVolume4 = property(
        _ctp.CThostFtdcDepthMarketDataField_AskVolume4_get,
        _ctp.CThostFtdcDepthMarketDataField_AskVolume4_set,
    )
    BidPrice5 = property(
        _ctp.CThostFtdcDepthMarketDataField_BidPrice5_get,
        _ctp.CThostFtdcDepthMarketDataField_BidPrice5_set,
    )
    BidVolume5 = property(
        _ctp.CThostFtdcDepthMarketDataField_BidVolume5_get,
        _ctp.CThostFtdcDepthMarketDataField_BidVolume5_set,
    )
    AskPrice5 = property(
        _ctp.CThostFtdcDepthMarketDataField_AskPrice5_get,
        _ctp.CThostFtdcDepthMarketDataField_AskPrice5_set,
    )
    AskVolume5 = property(
        _ctp.CThostFtdcDepthMarketDataField_AskVolume5_get,
        _ctp.CThostFtdcDepthMarketDataField_AskVolume5_set,
    )
    AveragePrice = property(
        _ctp.CThostFtdcDepthMarketDataField_AveragePrice_get,
        _ctp.CThostFtdcDepthMarketDataField_AveragePrice_set,
    )
    ActionDay = property(
        _ctp.CThostFtdcDepthMarketDataField_ActionDay_get,
        _ctp.CThostFtdcDepthMarketDataField_ActionDay_set,
    )
    InstrumentID = property(
        _ctp.CThostFtdcDepthMarketDataField_InstrumentID_get,
        _ctp.CThostFtdcDepthMarketDataField_InstrumentID_set,
    )
    ExchangeInstID = property(
        _ctp.CThostFtdcDepthMarketDataField_ExchangeInstID_get,
        _ctp.CThostFtdcDepthMarketDataField_ExchangeInstID_set,
    )
    BandingUpperPrice = property(
        _ctp.CThostFtdcDepthMarketDataField_BandingUpperPrice_get,
        _ctp.CThostFtdcDepthMarketDataField_BandingUpperPrice_set,
    )
    BandingLowerPrice = property(
        _ctp.CThostFtdcDepthMarketDataField_BandingLowerPrice_get,
        _ctp.CThostFtdcDepthMarketDataField_BandingLowerPrice_set,
    )

    def __init__(self):
        _ctp.CThostFtdcDepthMarketDataField_swiginit(
            self, _ctp.new_CThostFtdcDepthMarketDataField()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcDepthMarketDataField


# Register CThostFtdcDepthMarketDataField in _ctp:
_ctp.CThostFtdcDepthMarketDataField_swigregister(CThostFtdcDepthMarketDataField)


class CThostFtdcExchangeRateField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    BrokerID = property(
        _ctp.CThostFtdcExchangeRateField_BrokerID_get, _ctp.CThostFtdcExchangeRateField_BrokerID_set
    )
    FromCurrencyID = property(
        _ctp.CThostFtdcExchangeRateField_FromCurrencyID_get,
        _ctp.CThostFtdcExchangeRateField_FromCurrencyID_set,
    )
    FromCurrencyUnit = property(
        _ctp.CThostFtdcExchangeRateField_FromCurrencyUnit_get,
        _ctp.CThostFtdcExchangeRateField_FromCurrencyUnit_set,
    )
    ToCurrencyID = property(
        _ctp.CThostFtdcExchangeRateField_ToCurrencyID_get,
        _ctp.CThostFtdcExchangeRateField_ToCurrencyID_set,
    )
    ExchangeRate = property(
        _ctp.CThostFtdcExchangeRateField_ExchangeRate_get,
        _ctp.CThostFtdcExchangeRateField_ExchangeRate_set,
    )

    def __init__(self):
        _ctp.CThostFtdcExchangeRateField_swiginit(self, _ctp.new_CThostFtdcExchangeRateField())

    __swig_destroy__ = _ctp.delete_CThostFtdcExchangeRateField


# Register CThostFtdcExchangeRateField in _ctp:
_ctp.CThostFtdcExchangeRateField_swigregister(CThostFtdcExchangeRateField)


class CThostFtdcExchangeTradeField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    ExchangeID = property(
        _ctp.CThostFtdcExchangeTradeField_ExchangeID_get,
        _ctp.CThostFtdcExchangeTradeField_ExchangeID_set,
    )
    TradeID = property(
        _ctp.CThostFtdcExchangeTradeField_TradeID_get, _ctp.CThostFtdcExchangeTradeField_TradeID_set
    )
    Direction = property(
        _ctp.CThostFtdcExchangeTradeField_Direction_get,
        _ctp.CThostFtdcExchangeTradeField_Direction_set,
    )
    OrderSysID = property(
        _ctp.CThostFtdcExchangeTradeField_OrderSysID_get,
        _ctp.CThostFtdcExchangeTradeField_OrderSysID_set,
    )
    ParticipantID = property(
        _ctp.CThostFtdcExchangeTradeField_ParticipantID_get,
        _ctp.CThostFtdcExchangeTradeField_ParticipantID_set,
    )
    ClientID = property(
        _ctp.CThostFtdcExchangeTradeField_ClientID_get,
        _ctp.CThostFtdcExchangeTradeField_ClientID_set,
    )
    TradingRole = property(
        _ctp.CThostFtdcExchangeTradeField_TradingRole_get,
        _ctp.CThostFtdcExchangeTradeField_TradingRole_set,
    )
    reserve1 = property(
        _ctp.CThostFtdcExchangeTradeField_reserve1_get,
        _ctp.CThostFtdcExchangeTradeField_reserve1_set,
    )
    OffsetFlag = property(
        _ctp.CThostFtdcExchangeTradeField_OffsetFlag_get,
        _ctp.CThostFtdcExchangeTradeField_OffsetFlag_set,
    )
    HedgeFlag = property(
        _ctp.CThostFtdcExchangeTradeField_HedgeFlag_get,
        _ctp.CThostFtdcExchangeTradeField_HedgeFlag_set,
    )
    Price = property(
        _ctp.CThostFtdcExchangeTradeField_Price_get, _ctp.CThostFtdcExchangeTradeField_Price_set
    )
    Volume = property(
        _ctp.CThostFtdcExchangeTradeField_Volume_get, _ctp.CThostFtdcExchangeTradeField_Volume_set
    )
    TradeDate = property(
        _ctp.CThostFtdcExchangeTradeField_TradeDate_get,
        _ctp.CThostFtdcExchangeTradeField_TradeDate_set,
    )
    TradeTime = property(
        _ctp.CThostFtdcExchangeTradeField_TradeTime_get,
        _ctp.CThostFtdcExchangeTradeField_TradeTime_set,
    )
    TradeType = property(
        _ctp.CThostFtdcExchangeTradeField_TradeType_get,
        _ctp.CThostFtdcExchangeTradeField_TradeType_set,
    )
    PriceSource = property(
        _ctp.CThostFtdcExchangeTradeField_PriceSource_get,
        _ctp.CThostFtdcExchangeTradeField_PriceSource_set,
    )
    TraderID = property(
        _ctp.CThostFtdcExchangeTradeField_TraderID_get,
        _ctp.CThostFtdcExchangeTradeField_TraderID_set,
    )
    OrderLocalID = property(
        _ctp.CThostFtdcExchangeTradeField_OrderLocalID_get,
        _ctp.CThostFtdcExchangeTradeField_OrderLocalID_set,
    )
    ClearingPartID = property(
        _ctp.CThostFtdcExchangeTradeField_ClearingPartID_get,
        _ctp.CThostFtdcExchangeTradeField_ClearingPartID_set,
    )
    BusinessUnit = property(
        _ctp.CThostFtdcExchangeTradeField_BusinessUnit_get,
        _ctp.CThostFtdcExchangeTradeField_BusinessUnit_set,
    )
    SequenceNo = property(
        _ctp.CThostFtdcExchangeTradeField_SequenceNo_get,
        _ctp.CThostFtdcExchangeTradeField_SequenceNo_set,
    )
    TradeSource = property(
        _ctp.CThostFtdcExchangeTradeField_TradeSource_get,
        _ctp.CThostFtdcExchangeTradeField_TradeSource_set,
    )
    ExchangeInstID = property(
        _ctp.CThostFtdcExchangeTradeField_ExchangeInstID_get,
        _ctp.CThostFtdcExchangeTradeField_ExchangeInstID_set,
    )

    def __init__(self):
        _ctp.CThostFtdcExchangeTradeField_swiginit(self, _ctp.new_CThostFtdcExchangeTradeField())

    __swig_destroy__ = _ctp.delete_CThostFtdcExchangeTradeField


# Register CThostFtdcExchangeTradeField in _ctp:
_ctp.CThostFtdcExchangeTradeField_swigregister(CThostFtdcExchangeTradeField)


class CThostFtdcCombInstrumentGuardField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    BrokerID = property(
        _ctp.CThostFtdcCombInstrumentGuardField_BrokerID_get,
        _ctp.CThostFtdcCombInstrumentGuardField_BrokerID_set,
    )
    reserve1 = property(
        _ctp.CThostFtdcCombInstrumentGuardField_reserve1_get,
        _ctp.CThostFtdcCombInstrumentGuardField_reserve1_set,
    )
    GuarantRatio = property(
        _ctp.CThostFtdcCombInstrumentGuardField_GuarantRatio_get,
        _ctp.CThostFtdcCombInstrumentGuardField_GuarantRatio_set,
    )
    ExchangeID = property(
        _ctp.CThostFtdcCombInstrumentGuardField_ExchangeID_get,
        _ctp.CThostFtdcCombInstrumentGuardField_ExchangeID_set,
    )
    InstrumentID = property(
        _ctp.CThostFtdcCombInstrumentGuardField_InstrumentID_get,
        _ctp.CThostFtdcCombInstrumentGuardField_InstrumentID_set,
    )

    def __init__(self):
        _ctp.CThostFtdcCombInstrumentGuardField_swiginit(
            self, _ctp.new_CThostFtdcCombInstrumentGuardField()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcCombInstrumentGuardField


# Register CThostFtdcCombInstrumentGuardField in _ctp:
_ctp.CThostFtdcCombInstrumentGuardField_swigregister(CThostFtdcCombInstrumentGuardField)


class CThostFtdcProductExchRateField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    reserve1 = property(
        _ctp.CThostFtdcProductExchRateField_reserve1_get,
        _ctp.CThostFtdcProductExchRateField_reserve1_set,
    )
    QuoteCurrencyID = property(
        _ctp.CThostFtdcProductExchRateField_QuoteCurrencyID_get,
        _ctp.CThostFtdcProductExchRateField_QuoteCurrencyID_set,
    )
    ExchangeRate = property(
        _ctp.CThostFtdcProductExchRateField_ExchangeRate_get,
        _ctp.CThostFtdcProductExchRateField_ExchangeRate_set,
    )
    ExchangeID = property(
        _ctp.CThostFtdcProductExchRateField_ExchangeID_get,
        _ctp.CThostFtdcProductExchRateField_ExchangeID_set,
    )
    ProductID = property(
        _ctp.CThostFtdcProductExchRateField_ProductID_get,
        _ctp.CThostFtdcProductExchRateField_ProductID_set,
    )

    def __init__(self):
        _ctp.CThostFtdcProductExchRateField_swiginit(
            self, _ctp.new_CThostFtdcProductExchRateField()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcProductExchRateField


# Register CThostFtdcProductExchRateField in _ctp:
_ctp.CThostFtdcProductExchRateField_swigregister(CThostFtdcProductExchRateField)


class CThostFtdcMarketDataField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    TradingDay = property(
        _ctp.CThostFtdcMarketDataField_TradingDay_get, _ctp.CThostFtdcMarketDataField_TradingDay_set
    )
    reserve1 = property(
        _ctp.CThostFtdcMarketDataField_reserve1_get, _ctp.CThostFtdcMarketDataField_reserve1_set
    )
    ExchangeID = property(
        _ctp.CThostFtdcMarketDataField_ExchangeID_get, _ctp.CThostFtdcMarketDataField_ExchangeID_set
    )
    reserve2 = property(
        _ctp.CThostFtdcMarketDataField_reserve2_get, _ctp.CThostFtdcMarketDataField_reserve2_set
    )
    LastPrice = property(
        _ctp.CThostFtdcMarketDataField_LastPrice_get, _ctp.CThostFtdcMarketDataField_LastPrice_set
    )
    PreSettlementPrice = property(
        _ctp.CThostFtdcMarketDataField_PreSettlementPrice_get,
        _ctp.CThostFtdcMarketDataField_PreSettlementPrice_set,
    )
    PreClosePrice = property(
        _ctp.CThostFtdcMarketDataField_PreClosePrice_get,
        _ctp.CThostFtdcMarketDataField_PreClosePrice_set,
    )
    PreOpenInterest = property(
        _ctp.CThostFtdcMarketDataField_PreOpenInterest_get,
        _ctp.CThostFtdcMarketDataField_PreOpenInterest_set,
    )
    OpenPrice = property(
        _ctp.CThostFtdcMarketDataField_OpenPrice_get, _ctp.CThostFtdcMarketDataField_OpenPrice_set
    )
    HighestPrice = property(
        _ctp.CThostFtdcMarketDataField_HighestPrice_get,
        _ctp.CThostFtdcMarketDataField_HighestPrice_set,
    )
    LowestPrice = property(
        _ctp.CThostFtdcMarketDataField_LowestPrice_get,
        _ctp.CThostFtdcMarketDataField_LowestPrice_set,
    )
    Volume = property(
        _ctp.CThostFtdcMarketDataField_Volume_get, _ctp.CThostFtdcMarketDataField_Volume_set
    )
    Turnover = property(
        _ctp.CThostFtdcMarketDataField_Turnover_get, _ctp.CThostFtdcMarketDataField_Turnover_set
    )
    OpenInterest = property(
        _ctp.CThostFtdcMarketDataField_OpenInterest_get,
        _ctp.CThostFtdcMarketDataField_OpenInterest_set,
    )
    ClosePrice = property(
        _ctp.CThostFtdcMarketDataField_ClosePrice_get, _ctp.CThostFtdcMarketDataField_ClosePrice_set
    )
    SettlementPrice = property(
        _ctp.CThostFtdcMarketDataField_SettlementPrice_get,
        _ctp.CThostFtdcMarketDataField_SettlementPrice_set,
    )
    UpperLimitPrice = property(
        _ctp.CThostFtdcMarketDataField_UpperLimitPrice_get,
        _ctp.CThostFtdcMarketDataField_UpperLimitPrice_set,
    )
    LowerLimitPrice = property(
        _ctp.CThostFtdcMarketDataField_LowerLimitPrice_get,
        _ctp.CThostFtdcMarketDataField_LowerLimitPrice_set,
    )
    PreDelta = property(
        _ctp.CThostFtdcMarketDataField_PreDelta_get, _ctp.CThostFtdcMarketDataField_PreDelta_set
    )
    CurrDelta = property(
        _ctp.CThostFtdcMarketDataField_CurrDelta_get, _ctp.CThostFtdcMarketDataField_CurrDelta_set
    )
    UpdateTime = property(
        _ctp.CThostFtdcMarketDataField_UpdateTime_get, _ctp.CThostFtdcMarketDataField_UpdateTime_set
    )
    UpdateMillisec = property(
        _ctp.CThostFtdcMarketDataField_UpdateMillisec_get,
        _ctp.CThostFtdcMarketDataField_UpdateMillisec_set,
    )
    ActionDay = property(
        _ctp.CThostFtdcMarketDataField_ActionDay_get, _ctp.CThostFtdcMarketDataField_ActionDay_set
    )
    InstrumentID = property(
        _ctp.CThostFtdcMarketDataField_InstrumentID_get,
        _ctp.CThostFtdcMarketDataField_InstrumentID_set,
    )
    ExchangeInstID = property(
        _ctp.CThostFtdcMarketDataField_ExchangeInstID_get,
        _ctp.CThostFtdcMarketDataField_ExchangeInstID_set,
    )

    def __init__(self):
        _ctp.CThostFtdcMarketDataField_swiginit(self, _ctp.new_CThostFtdcMarketDataField())

    __swig_destroy__ = _ctp.delete_CThostFtdcMarketDataField


# Register CThostFtdcMarketDataField in _ctp:
_ctp.CThostFtdcMarketDataField_swigregister(CThostFtdcMarketDataField)


class CThostFtdcMarketDataBaseField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    TradingDay = property(
        _ctp.CThostFtdcMarketDataBaseField_TradingDay_get,
        _ctp.CThostFtdcMarketDataBaseField_TradingDay_set,
    )
    PreSettlementPrice = property(
        _ctp.CThostFtdcMarketDataBaseField_PreSettlementPrice_get,
        _ctp.CThostFtdcMarketDataBaseField_PreSettlementPrice_set,
    )
    PreClosePrice = property(
        _ctp.CThostFtdcMarketDataBaseField_PreClosePrice_get,
        _ctp.CThostFtdcMarketDataBaseField_PreClosePrice_set,
    )
    PreOpenInterest = property(
        _ctp.CThostFtdcMarketDataBaseField_PreOpenInterest_get,
        _ctp.CThostFtdcMarketDataBaseField_PreOpenInterest_set,
    )
    PreDelta = property(
        _ctp.CThostFtdcMarketDataBaseField_PreDelta_get,
        _ctp.CThostFtdcMarketDataBaseField_PreDelta_set,
    )

    def __init__(self):
        _ctp.CThostFtdcMarketDataBaseField_swiginit(self, _ctp.new_CThostFtdcMarketDataBaseField())

    __swig_destroy__ = _ctp.delete_CThostFtdcMarketDataBaseField


# Register CThostFtdcMarketDataBaseField in _ctp:
_ctp.CThostFtdcMarketDataBaseField_swigregister(CThostFtdcMarketDataBaseField)


class CThostFtdcMarketDataStaticField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    OpenPrice = property(
        _ctp.CThostFtdcMarketDataStaticField_OpenPrice_get,
        _ctp.CThostFtdcMarketDataStaticField_OpenPrice_set,
    )
    HighestPrice = property(
        _ctp.CThostFtdcMarketDataStaticField_HighestPrice_get,
        _ctp.CThostFtdcMarketDataStaticField_HighestPrice_set,
    )
    LowestPrice = property(
        _ctp.CThostFtdcMarketDataStaticField_LowestPrice_get,
        _ctp.CThostFtdcMarketDataStaticField_LowestPrice_set,
    )
    ClosePrice = property(
        _ctp.CThostFtdcMarketDataStaticField_ClosePrice_get,
        _ctp.CThostFtdcMarketDataStaticField_ClosePrice_set,
    )
    UpperLimitPrice = property(
        _ctp.CThostFtdcMarketDataStaticField_UpperLimitPrice_get,
        _ctp.CThostFtdcMarketDataStaticField_UpperLimitPrice_set,
    )
    LowerLimitPrice = property(
        _ctp.CThostFtdcMarketDataStaticField_LowerLimitPrice_get,
        _ctp.CThostFtdcMarketDataStaticField_LowerLimitPrice_set,
    )
    SettlementPrice = property(
        _ctp.CThostFtdcMarketDataStaticField_SettlementPrice_get,
        _ctp.CThostFtdcMarketDataStaticField_SettlementPrice_set,
    )
    CurrDelta = property(
        _ctp.CThostFtdcMarketDataStaticField_CurrDelta_get,
        _ctp.CThostFtdcMarketDataStaticField_CurrDelta_set,
    )

    def __init__(self):
        _ctp.CThostFtdcMarketDataStaticField_swiginit(
            self, _ctp.new_CThostFtdcMarketDataStaticField()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcMarketDataStaticField


# Register CThostFtdcMarketDataStaticField in _ctp:
_ctp.CThostFtdcMarketDataStaticField_swigregister(CThostFtdcMarketDataStaticField)


class CThostFtdcMarketDataLastMatchField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    LastPrice = property(
        _ctp.CThostFtdcMarketDataLastMatchField_LastPrice_get,
        _ctp.CThostFtdcMarketDataLastMatchField_LastPrice_set,
    )
    Volume = property(
        _ctp.CThostFtdcMarketDataLastMatchField_Volume_get,
        _ctp.CThostFtdcMarketDataLastMatchField_Volume_set,
    )
    Turnover = property(
        _ctp.CThostFtdcMarketDataLastMatchField_Turnover_get,
        _ctp.CThostFtdcMarketDataLastMatchField_Turnover_set,
    )
    OpenInterest = property(
        _ctp.CThostFtdcMarketDataLastMatchField_OpenInterest_get,
        _ctp.CThostFtdcMarketDataLastMatchField_OpenInterest_set,
    )

    def __init__(self):
        _ctp.CThostFtdcMarketDataLastMatchField_swiginit(
            self, _ctp.new_CThostFtdcMarketDataLastMatchField()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcMarketDataLastMatchField


# Register CThostFtdcMarketDataLastMatchField in _ctp:
_ctp.CThostFtdcMarketDataLastMatchField_swigregister(CThostFtdcMarketDataLastMatchField)


class CThostFtdcMarketDataBestPriceField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    BidPrice1 = property(
        _ctp.CThostFtdcMarketDataBestPriceField_BidPrice1_get,
        _ctp.CThostFtdcMarketDataBestPriceField_BidPrice1_set,
    )
    BidVolume1 = property(
        _ctp.CThostFtdcMarketDataBestPriceField_BidVolume1_get,
        _ctp.CThostFtdcMarketDataBestPriceField_BidVolume1_set,
    )
    AskPrice1 = property(
        _ctp.CThostFtdcMarketDataBestPriceField_AskPrice1_get,
        _ctp.CThostFtdcMarketDataBestPriceField_AskPrice1_set,
    )
    AskVolume1 = property(
        _ctp.CThostFtdcMarketDataBestPriceField_AskVolume1_get,
        _ctp.CThostFtdcMarketDataBestPriceField_AskVolume1_set,
    )

    def __init__(self):
        _ctp.CThostFtdcMarketDataBestPriceField_swiginit(
            self, _ctp.new_CThostFtdcMarketDataBestPriceField()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcMarketDataBestPriceField


# Register CThostFtdcMarketDataBestPriceField in _ctp:
_ctp.CThostFtdcMarketDataBestPriceField_swigregister(CThostFtdcMarketDataBestPriceField)


class CThostFtdcMarketDataBid23Field:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    BidPrice2 = property(
        _ctp.CThostFtdcMarketDataBid23Field_BidPrice2_get,
        _ctp.CThostFtdcMarketDataBid23Field_BidPrice2_set,
    )
    BidVolume2 = property(
        _ctp.CThostFtdcMarketDataBid23Field_BidVolume2_get,
        _ctp.CThostFtdcMarketDataBid23Field_BidVolume2_set,
    )
    BidPrice3 = property(
        _ctp.CThostFtdcMarketDataBid23Field_BidPrice3_get,
        _ctp.CThostFtdcMarketDataBid23Field_BidPrice3_set,
    )
    BidVolume3 = property(
        _ctp.CThostFtdcMarketDataBid23Field_BidVolume3_get,
        _ctp.CThostFtdcMarketDataBid23Field_BidVolume3_set,
    )

    def __init__(self):
        _ctp.CThostFtdcMarketDataBid23Field_swiginit(
            self, _ctp.new_CThostFtdcMarketDataBid23Field()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcMarketDataBid23Field


# Register CThostFtdcMarketDataBid23Field in _ctp:
_ctp.CThostFtdcMarketDataBid23Field_swigregister(CThostFtdcMarketDataBid23Field)


class CThostFtdcMarketDataAsk23Field:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    AskPrice2 = property(
        _ctp.CThostFtdcMarketDataAsk23Field_AskPrice2_get,
        _ctp.CThostFtdcMarketDataAsk23Field_AskPrice2_set,
    )
    AskVolume2 = property(
        _ctp.CThostFtdcMarketDataAsk23Field_AskVolume2_get,
        _ctp.CThostFtdcMarketDataAsk23Field_AskVolume2_set,
    )
    AskPrice3 = property(
        _ctp.CThostFtdcMarketDataAsk23Field_AskPrice3_get,
        _ctp.CThostFtdcMarketDataAsk23Field_AskPrice3_set,
    )
    AskVolume3 = property(
        _ctp.CThostFtdcMarketDataAsk23Field_AskVolume3_get,
        _ctp.CThostFtdcMarketDataAsk23Field_AskVolume3_set,
    )

    def __init__(self):
        _ctp.CThostFtdcMarketDataAsk23Field_swiginit(
            self, _ctp.new_CThostFtdcMarketDataAsk23Field()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcMarketDataAsk23Field


# Register CThostFtdcMarketDataAsk23Field in _ctp:
_ctp.CThostFtdcMarketDataAsk23Field_swigregister(CThostFtdcMarketDataAsk23Field)


class CThostFtdcMarketDataBid45Field:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    BidPrice4 = property(
        _ctp.CThostFtdcMarketDataBid45Field_BidPrice4_get,
        _ctp.CThostFtdcMarketDataBid45Field_BidPrice4_set,
    )
    BidVolume4 = property(
        _ctp.CThostFtdcMarketDataBid45Field_BidVolume4_get,
        _ctp.CThostFtdcMarketDataBid45Field_BidVolume4_set,
    )
    BidPrice5 = property(
        _ctp.CThostFtdcMarketDataBid45Field_BidPrice5_get,
        _ctp.CThostFtdcMarketDataBid45Field_BidPrice5_set,
    )
    BidVolume5 = property(
        _ctp.CThostFtdcMarketDataBid45Field_BidVolume5_get,
        _ctp.CThostFtdcMarketDataBid45Field_BidVolume5_set,
    )

    def __init__(self):
        _ctp.CThostFtdcMarketDataBid45Field_swiginit(
            self, _ctp.new_CThostFtdcMarketDataBid45Field()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcMarketDataBid45Field


# Register CThostFtdcMarketDataBid45Field in _ctp:
_ctp.CThostFtdcMarketDataBid45Field_swigregister(CThostFtdcMarketDataBid45Field)


class CThostFtdcMarketDataAsk45Field:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    AskPrice4 = property(
        _ctp.CThostFtdcMarketDataAsk45Field_AskPrice4_get,
        _ctp.CThostFtdcMarketDataAsk45Field_AskPrice4_set,
    )
    AskVolume4 = property(
        _ctp.CThostFtdcMarketDataAsk45Field_AskVolume4_get,
        _ctp.CThostFtdcMarketDataAsk45Field_AskVolume4_set,
    )
    AskPrice5 = property(
        _ctp.CThostFtdcMarketDataAsk45Field_AskPrice5_get,
        _ctp.CThostFtdcMarketDataAsk45Field_AskPrice5_set,
    )
    AskVolume5 = property(
        _ctp.CThostFtdcMarketDataAsk45Field_AskVolume5_get,
        _ctp.CThostFtdcMarketDataAsk45Field_AskVolume5_set,
    )

    def __init__(self):
        _ctp.CThostFtdcMarketDataAsk45Field_swiginit(
            self, _ctp.new_CThostFtdcMarketDataAsk45Field()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcMarketDataAsk45Field


# Register CThostFtdcMarketDataAsk45Field in _ctp:
_ctp.CThostFtdcMarketDataAsk45Field_swigregister(CThostFtdcMarketDataAsk45Field)


class CThostFtdcMarketDataUpdateTimeField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    reserve1 = property(
        _ctp.CThostFtdcMarketDataUpdateTimeField_reserve1_get,
        _ctp.CThostFtdcMarketDataUpdateTimeField_reserve1_set,
    )
    UpdateTime = property(
        _ctp.CThostFtdcMarketDataUpdateTimeField_UpdateTime_get,
        _ctp.CThostFtdcMarketDataUpdateTimeField_UpdateTime_set,
    )
    UpdateMillisec = property(
        _ctp.CThostFtdcMarketDataUpdateTimeField_UpdateMillisec_get,
        _ctp.CThostFtdcMarketDataUpdateTimeField_UpdateMillisec_set,
    )
    ActionDay = property(
        _ctp.CThostFtdcMarketDataUpdateTimeField_ActionDay_get,
        _ctp.CThostFtdcMarketDataUpdateTimeField_ActionDay_set,
    )
    InstrumentID = property(
        _ctp.CThostFtdcMarketDataUpdateTimeField_InstrumentID_get,
        _ctp.CThostFtdcMarketDataUpdateTimeField_InstrumentID_set,
    )

    def __init__(self):
        _ctp.CThostFtdcMarketDataUpdateTimeField_swiginit(
            self, _ctp.new_CThostFtdcMarketDataUpdateTimeField()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcMarketDataUpdateTimeField


# Register CThostFtdcMarketDataUpdateTimeField in _ctp:
_ctp.CThostFtdcMarketDataUpdateTimeField_swigregister(CThostFtdcMarketDataUpdateTimeField)


class CThostFtdcMarketDataBandingPriceField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    BandingUpperPrice = property(
        _ctp.CThostFtdcMarketDataBandingPriceField_BandingUpperPrice_get,
        _ctp.CThostFtdcMarketDataBandingPriceField_BandingUpperPrice_set,
    )
    BandingLowerPrice = property(
        _ctp.CThostFtdcMarketDataBandingPriceField_BandingLowerPrice_get,
        _ctp.CThostFtdcMarketDataBandingPriceField_BandingLowerPrice_set,
    )

    def __init__(self):
        _ctp.CThostFtdcMarketDataBandingPriceField_swiginit(
            self, _ctp.new_CThostFtdcMarketDataBandingPriceField()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcMarketDataBandingPriceField


# Register CThostFtdcMarketDataBandingPriceField in _ctp:
_ctp.CThostFtdcMarketDataBandingPriceField_swigregister(CThostFtdcMarketDataBandingPriceField)


class CThostFtdcMarketDataExchangeField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    ExchangeID = property(
        _ctp.CThostFtdcMarketDataExchangeField_ExchangeID_get,
        _ctp.CThostFtdcMarketDataExchangeField_ExchangeID_set,
    )

    def __init__(self):
        _ctp.CThostFtdcMarketDataExchangeField_swiginit(
            self, _ctp.new_CThostFtdcMarketDataExchangeField()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcMarketDataExchangeField


# Register CThostFtdcMarketDataExchangeField in _ctp:
_ctp.CThostFtdcMarketDataExchangeField_swigregister(CThostFtdcMarketDataExchangeField)


class CThostFtdcSpecificInstrumentField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    reserve1 = property(
        _ctp.CThostFtdcSpecificInstrumentField_reserve1_get,
        _ctp.CThostFtdcSpecificInstrumentField_reserve1_set,
    )
    InstrumentID = property(
        _ctp.CThostFtdcSpecificInstrumentField_InstrumentID_get,
        _ctp.CThostFtdcSpecificInstrumentField_InstrumentID_set,
    )

    def __init__(self):
        _ctp.CThostFtdcSpecificInstrumentField_swiginit(
            self, _ctp.new_CThostFtdcSpecificInstrumentField()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcSpecificInstrumentField


# Register CThostFtdcSpecificInstrumentField in _ctp:
_ctp.CThostFtdcSpecificInstrumentField_swigregister(CThostFtdcSpecificInstrumentField)


class CThostFtdcInstrumentStatusField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    ExchangeID = property(
        _ctp.CThostFtdcInstrumentStatusField_ExchangeID_get,
        _ctp.CThostFtdcInstrumentStatusField_ExchangeID_set,
    )
    reserve1 = property(
        _ctp.CThostFtdcInstrumentStatusField_reserve1_get,
        _ctp.CThostFtdcInstrumentStatusField_reserve1_set,
    )
    SettlementGroupID = property(
        _ctp.CThostFtdcInstrumentStatusField_SettlementGroupID_get,
        _ctp.CThostFtdcInstrumentStatusField_SettlementGroupID_set,
    )
    reserve2 = property(
        _ctp.CThostFtdcInstrumentStatusField_reserve2_get,
        _ctp.CThostFtdcInstrumentStatusField_reserve2_set,
    )
    InstrumentStatus = property(
        _ctp.CThostFtdcInstrumentStatusField_InstrumentStatus_get,
        _ctp.CThostFtdcInstrumentStatusField_InstrumentStatus_set,
    )
    TradingSegmentSN = property(
        _ctp.CThostFtdcInstrumentStatusField_TradingSegmentSN_get,
        _ctp.CThostFtdcInstrumentStatusField_TradingSegmentSN_set,
    )
    EnterTime = property(
        _ctp.CThostFtdcInstrumentStatusField_EnterTime_get,
        _ctp.CThostFtdcInstrumentStatusField_EnterTime_set,
    )
    EnterReason = property(
        _ctp.CThostFtdcInstrumentStatusField_EnterReason_get,
        _ctp.CThostFtdcInstrumentStatusField_EnterReason_set,
    )
    ExchangeInstID = property(
        _ctp.CThostFtdcInstrumentStatusField_ExchangeInstID_get,
        _ctp.CThostFtdcInstrumentStatusField_ExchangeInstID_set,
    )
    InstrumentID = property(
        _ctp.CThostFtdcInstrumentStatusField_InstrumentID_get,
        _ctp.CThostFtdcInstrumentStatusField_InstrumentID_set,
    )

    def __init__(self):
        _ctp.CThostFtdcInstrumentStatusField_swiginit(
            self, _ctp.new_CThostFtdcInstrumentStatusField()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcInstrumentStatusField


# Register CThostFtdcInstrumentStatusField in _ctp:
_ctp.CThostFtdcInstrumentStatusField_swigregister(CThostFtdcInstrumentStatusField)


class CThostFtdcMarketDataAveragePriceField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    AveragePrice = property(
        _ctp.CThostFtdcMarketDataAveragePriceField_AveragePrice_get,
        _ctp.CThostFtdcMarketDataAveragePriceField_AveragePrice_set,
    )

    def __init__(self):
        _ctp.CThostFtdcMarketDataAveragePriceField_swiginit(
            self, _ctp.new_CThostFtdcMarketDataAveragePriceField()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcMarketDataAveragePriceField


# Register CThostFtdcMarketDataAveragePriceField in _ctp:
_ctp.CThostFtdcMarketDataAveragePriceField_swigregister(CThostFtdcMarketDataAveragePriceField)


class CThostFtdcExchangeSequenceField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    ExchangeID = property(
        _ctp.CThostFtdcExchangeSequenceField_ExchangeID_get,
        _ctp.CThostFtdcExchangeSequenceField_ExchangeID_set,
    )
    SequenceNo = property(
        _ctp.CThostFtdcExchangeSequenceField_SequenceNo_get,
        _ctp.CThostFtdcExchangeSequenceField_SequenceNo_set,
    )
    MarketStatus = property(
        _ctp.CThostFtdcExchangeSequenceField_MarketStatus_get,
        _ctp.CThostFtdcExchangeSequenceField_MarketStatus_set,
    )

    def __init__(self):
        _ctp.CThostFtdcExchangeSequenceField_swiginit(
            self, _ctp.new_CThostFtdcExchangeSequenceField()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcExchangeSequenceField


# Register CThostFtdcExchangeSequenceField in _ctp:
_ctp.CThostFtdcExchangeSequenceField_swigregister(CThostFtdcExchangeSequenceField)


class CThostFtdcProductGroupField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    reserve1 = property(
        _ctp.CThostFtdcProductGroupField_reserve1_get, _ctp.CThostFtdcProductGroupField_reserve1_set
    )
    ExchangeID = property(
        _ctp.CThostFtdcProductGroupField_ExchangeID_get,
        _ctp.CThostFtdcProductGroupField_ExchangeID_set,
    )
    reserve2 = property(
        _ctp.CThostFtdcProductGroupField_reserve2_get, _ctp.CThostFtdcProductGroupField_reserve2_set
    )
    ProductID = property(
        _ctp.CThostFtdcProductGroupField_ProductID_get,
        _ctp.CThostFtdcProductGroupField_ProductID_set,
    )
    ProductGroupID = property(
        _ctp.CThostFtdcProductGroupField_ProductGroupID_get,
        _ctp.CThostFtdcProductGroupField_ProductGroupID_set,
    )

    def __init__(self):
        _ctp.CThostFtdcProductGroupField_swiginit(self, _ctp.new_CThostFtdcProductGroupField())

    __swig_destroy__ = _ctp.delete_CThostFtdcProductGroupField


# Register CThostFtdcProductGroupField in _ctp:
_ctp.CThostFtdcProductGroupField_swigregister(CThostFtdcProductGroupField)


class CThostFtdcMulticastInstrumentField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    TopicID = property(
        _ctp.CThostFtdcMulticastInstrumentField_TopicID_get,
        _ctp.CThostFtdcMulticastInstrumentField_TopicID_set,
    )
    reserve1 = property(
        _ctp.CThostFtdcMulticastInstrumentField_reserve1_get,
        _ctp.CThostFtdcMulticastInstrumentField_reserve1_set,
    )
    InstrumentNo = property(
        _ctp.CThostFtdcMulticastInstrumentField_InstrumentNo_get,
        _ctp.CThostFtdcMulticastInstrumentField_InstrumentNo_set,
    )
    CodePrice = property(
        _ctp.CThostFtdcMulticastInstrumentField_CodePrice_get,
        _ctp.CThostFtdcMulticastInstrumentField_CodePrice_set,
    )
    VolumeMultiple = property(
        _ctp.CThostFtdcMulticastInstrumentField_VolumeMultiple_get,
        _ctp.CThostFtdcMulticastInstrumentField_VolumeMultiple_set,
    )
    PriceTick = property(
        _ctp.CThostFtdcMulticastInstrumentField_PriceTick_get,
        _ctp.CThostFtdcMulticastInstrumentField_PriceTick_set,
    )
    InstrumentID = property(
        _ctp.CThostFtdcMulticastInstrumentField_InstrumentID_get,
        _ctp.CThostFtdcMulticastInstrumentField_InstrumentID_set,
    )

    def __init__(self):
        _ctp.CThostFtdcMulticastInstrumentField_swiginit(
            self, _ctp.new_CThostFtdcMulticastInstrumentField()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcMulticastInstrumentField


# Register CThostFtdcMulticastInstrumentField in _ctp:
_ctp.CThostFtdcMulticastInstrumentField_swigregister(CThostFtdcMulticastInstrumentField)


class CThostFtdcFrontInfoField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    FrontAddr = property(
        _ctp.CThostFtdcFrontInfoField_FrontAddr_get, _ctp.CThostFtdcFrontInfoField_FrontAddr_set
    )
    QryFreq = property(
        _ctp.CThostFtdcFrontInfoField_QryFreq_get, _ctp.CThostFtdcFrontInfoField_QryFreq_set
    )
    FTDPkgFreq = property(
        _ctp.CThostFtdcFrontInfoField_FTDPkgFreq_get, _ctp.CThostFtdcFrontInfoField_FTDPkgFreq_set
    )

    def __init__(self):
        _ctp.CThostFtdcFrontInfoField_swiginit(self, _ctp.new_CThostFtdcFrontInfoField())

    __swig_destroy__ = _ctp.delete_CThostFtdcFrontInfoField


# Register CThostFtdcFrontInfoField in _ctp:
_ctp.CThostFtdcFrontInfoField_swigregister(CThostFtdcFrontInfoField)

__all__ = [
    "CThostFtdcDisseminationField",
    "CThostFtdcExchangeField",
    "CThostFtdcProductField",
    "CThostFtdcInstrumentField",
    "CThostFtdcDepthMarketDataField",
    "CThostFtdcExchangeRateField",
    "CThostFtdcExchangeTradeField",
    "CThostFtdcCombInstrumentGuardField",
    "CThostFtdcProductExchRateField",
    "CThostFtdcMarketDataField",
    "CThostFtdcMarketDataBaseField",
    "CThostFtdcMarketDataStaticField",
    "CThostFtdcMarketDataLastMatchField",
    "CThostFtdcMarketDataBestPriceField",
    "CThostFtdcMarketDataBid23Field",
    "CThostFtdcMarketDataAsk23Field",
    "CThostFtdcMarketDataBid45Field",
    "CThostFtdcMarketDataAsk45Field",
    "CThostFtdcMarketDataUpdateTimeField",
    "CThostFtdcMarketDataBandingPriceField",
    "CThostFtdcMarketDataExchangeField",
    "CThostFtdcSpecificInstrumentField",
    "CThostFtdcInstrumentStatusField",
    "CThostFtdcMarketDataAveragePriceField",
    "CThostFtdcExchangeSequenceField",
    "CThostFtdcProductGroupField",
    "CThostFtdcMulticastInstrumentField",
    "CThostFtdcFrontInfoField",
]
