# AUTO-GENERATED by split_ctp_wrapper.py — DO NOT EDIT
"""CTP 持仓相关结构"""

from __future__ import annotations

from ._ctp_base import _ctp, _swig_repr


class CThostFtdcInvestorPositionField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    reserve1 = property(
        _ctp.CThostFtdcInvestorPositionField_reserve1_get,
        _ctp.CThostFtdcInvestorPositionField_reserve1_set,
    )
    BrokerID = property(
        _ctp.CThostFtdcInvestorPositionField_BrokerID_get,
        _ctp.CThostFtdcInvestorPositionField_BrokerID_set,
    )
    InvestorID = property(
        _ctp.CThostFtdcInvestorPositionField_InvestorID_get,
        _ctp.CThostFtdcInvestorPositionField_InvestorID_set,
    )
    PosiDirection = property(
        _ctp.CThostFtdcInvestorPositionField_PosiDirection_get,
        _ctp.CThostFtdcInvestorPositionField_PosiDirection_set,
    )
    HedgeFlag = property(
        _ctp.CThostFtdcInvestorPositionField_HedgeFlag_get,
        _ctp.CThostFtdcInvestorPositionField_HedgeFlag_set,
    )
    PositionDate = property(
        _ctp.CThostFtdcInvestorPositionField_PositionDate_get,
        _ctp.CThostFtdcInvestorPositionField_PositionDate_set,
    )
    YdPosition = property(
        _ctp.CThostFtdcInvestorPositionField_YdPosition_get,
        _ctp.CThostFtdcInvestorPositionField_YdPosition_set,
    )
    Position = property(
        _ctp.CThostFtdcInvestorPositionField_Position_get,
        _ctp.CThostFtdcInvestorPositionField_Position_set,
    )
    LongFrozen = property(
        _ctp.CThostFtdcInvestorPositionField_LongFrozen_get,
        _ctp.CThostFtdcInvestorPositionField_LongFrozen_set,
    )
    ShortFrozen = property(
        _ctp.CThostFtdcInvestorPositionField_ShortFrozen_get,
        _ctp.CThostFtdcInvestorPositionField_ShortFrozen_set,
    )
    LongFrozenAmount = property(
        _ctp.CThostFtdcInvestorPositionField_LongFrozenAmount_get,
        _ctp.CThostFtdcInvestorPositionField_LongFrozenAmount_set,
    )
    ShortFrozenAmount = property(
        _ctp.CThostFtdcInvestorPositionField_ShortFrozenAmount_get,
        _ctp.CThostFtdcInvestorPositionField_ShortFrozenAmount_set,
    )
    OpenVolume = property(
        _ctp.CThostFtdcInvestorPositionField_OpenVolume_get,
        _ctp.CThostFtdcInvestorPositionField_OpenVolume_set,
    )
    CloseVolume = property(
        _ctp.CThostFtdcInvestorPositionField_CloseVolume_get,
        _ctp.CThostFtdcInvestorPositionField_CloseVolume_set,
    )
    OpenAmount = property(
        _ctp.CThostFtdcInvestorPositionField_OpenAmount_get,
        _ctp.CThostFtdcInvestorPositionField_OpenAmount_set,
    )
    CloseAmount = property(
        _ctp.CThostFtdcInvestorPositionField_CloseAmount_get,
        _ctp.CThostFtdcInvestorPositionField_CloseAmount_set,
    )
    PositionCost = property(
        _ctp.CThostFtdcInvestorPositionField_PositionCost_get,
        _ctp.CThostFtdcInvestorPositionField_PositionCost_set,
    )
    PreMargin = property(
        _ctp.CThostFtdcInvestorPositionField_PreMargin_get,
        _ctp.CThostFtdcInvestorPositionField_PreMargin_set,
    )
    UseMargin = property(
        _ctp.CThostFtdcInvestorPositionField_UseMargin_get,
        _ctp.CThostFtdcInvestorPositionField_UseMargin_set,
    )
    FrozenMargin = property(
        _ctp.CThostFtdcInvestorPositionField_FrozenMargin_get,
        _ctp.CThostFtdcInvestorPositionField_FrozenMargin_set,
    )
    FrozenCash = property(
        _ctp.CThostFtdcInvestorPositionField_FrozenCash_get,
        _ctp.CThostFtdcInvestorPositionField_FrozenCash_set,
    )
    FrozenCommission = property(
        _ctp.CThostFtdcInvestorPositionField_FrozenCommission_get,
        _ctp.CThostFtdcInvestorPositionField_FrozenCommission_set,
    )
    CashIn = property(
        _ctp.CThostFtdcInvestorPositionField_CashIn_get,
        _ctp.CThostFtdcInvestorPositionField_CashIn_set,
    )
    Commission = property(
        _ctp.CThostFtdcInvestorPositionField_Commission_get,
        _ctp.CThostFtdcInvestorPositionField_Commission_set,
    )
    CloseProfit = property(
        _ctp.CThostFtdcInvestorPositionField_CloseProfit_get,
        _ctp.CThostFtdcInvestorPositionField_CloseProfit_set,
    )
    PositionProfit = property(
        _ctp.CThostFtdcInvestorPositionField_PositionProfit_get,
        _ctp.CThostFtdcInvestorPositionField_PositionProfit_set,
    )
    PreSettlementPrice = property(
        _ctp.CThostFtdcInvestorPositionField_PreSettlementPrice_get,
        _ctp.CThostFtdcInvestorPositionField_PreSettlementPrice_set,
    )
    SettlementPrice = property(
        _ctp.CThostFtdcInvestorPositionField_SettlementPrice_get,
        _ctp.CThostFtdcInvestorPositionField_SettlementPrice_set,
    )
    TradingDay = property(
        _ctp.CThostFtdcInvestorPositionField_TradingDay_get,
        _ctp.CThostFtdcInvestorPositionField_TradingDay_set,
    )
    SettlementID = property(
        _ctp.CThostFtdcInvestorPositionField_SettlementID_get,
        _ctp.CThostFtdcInvestorPositionField_SettlementID_set,
    )
    OpenCost = property(
        _ctp.CThostFtdcInvestorPositionField_OpenCost_get,
        _ctp.CThostFtdcInvestorPositionField_OpenCost_set,
    )
    ExchangeMargin = property(
        _ctp.CThostFtdcInvestorPositionField_ExchangeMargin_get,
        _ctp.CThostFtdcInvestorPositionField_ExchangeMargin_set,
    )
    CombPosition = property(
        _ctp.CThostFtdcInvestorPositionField_CombPosition_get,
        _ctp.CThostFtdcInvestorPositionField_CombPosition_set,
    )
    CombLongFrozen = property(
        _ctp.CThostFtdcInvestorPositionField_CombLongFrozen_get,
        _ctp.CThostFtdcInvestorPositionField_CombLongFrozen_set,
    )
    CombShortFrozen = property(
        _ctp.CThostFtdcInvestorPositionField_CombShortFrozen_get,
        _ctp.CThostFtdcInvestorPositionField_CombShortFrozen_set,
    )
    CloseProfitByDate = property(
        _ctp.CThostFtdcInvestorPositionField_CloseProfitByDate_get,
        _ctp.CThostFtdcInvestorPositionField_CloseProfitByDate_set,
    )
    CloseProfitByTrade = property(
        _ctp.CThostFtdcInvestorPositionField_CloseProfitByTrade_get,
        _ctp.CThostFtdcInvestorPositionField_CloseProfitByTrade_set,
    )
    TodayPosition = property(
        _ctp.CThostFtdcInvestorPositionField_TodayPosition_get,
        _ctp.CThostFtdcInvestorPositionField_TodayPosition_set,
    )
    MarginRateByMoney = property(
        _ctp.CThostFtdcInvestorPositionField_MarginRateByMoney_get,
        _ctp.CThostFtdcInvestorPositionField_MarginRateByMoney_set,
    )
    MarginRateByVolume = property(
        _ctp.CThostFtdcInvestorPositionField_MarginRateByVolume_get,
        _ctp.CThostFtdcInvestorPositionField_MarginRateByVolume_set,
    )
    StrikeFrozen = property(
        _ctp.CThostFtdcInvestorPositionField_StrikeFrozen_get,
        _ctp.CThostFtdcInvestorPositionField_StrikeFrozen_set,
    )
    StrikeFrozenAmount = property(
        _ctp.CThostFtdcInvestorPositionField_StrikeFrozenAmount_get,
        _ctp.CThostFtdcInvestorPositionField_StrikeFrozenAmount_set,
    )
    AbandonFrozen = property(
        _ctp.CThostFtdcInvestorPositionField_AbandonFrozen_get,
        _ctp.CThostFtdcInvestorPositionField_AbandonFrozen_set,
    )
    ExchangeID = property(
        _ctp.CThostFtdcInvestorPositionField_ExchangeID_get,
        _ctp.CThostFtdcInvestorPositionField_ExchangeID_set,
    )
    YdStrikeFrozen = property(
        _ctp.CThostFtdcInvestorPositionField_YdStrikeFrozen_get,
        _ctp.CThostFtdcInvestorPositionField_YdStrikeFrozen_set,
    )
    InvestUnitID = property(
        _ctp.CThostFtdcInvestorPositionField_InvestUnitID_get,
        _ctp.CThostFtdcInvestorPositionField_InvestUnitID_set,
    )
    PositionCostOffset = property(
        _ctp.CThostFtdcInvestorPositionField_PositionCostOffset_get,
        _ctp.CThostFtdcInvestorPositionField_PositionCostOffset_set,
    )
    TasPosition = property(
        _ctp.CThostFtdcInvestorPositionField_TasPosition_get,
        _ctp.CThostFtdcInvestorPositionField_TasPosition_set,
    )
    TasPositionCost = property(
        _ctp.CThostFtdcInvestorPositionField_TasPositionCost_get,
        _ctp.CThostFtdcInvestorPositionField_TasPositionCost_set,
    )
    InstrumentID = property(
        _ctp.CThostFtdcInvestorPositionField_InstrumentID_get,
        _ctp.CThostFtdcInvestorPositionField_InstrumentID_set,
    )

    def __init__(self):
        _ctp.CThostFtdcInvestorPositionField_swiginit(
            self, _ctp.new_CThostFtdcInvestorPositionField()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcInvestorPositionField


# Register CThostFtdcInvestorPositionField in _ctp:
_ctp.CThostFtdcInvestorPositionField_swigregister(CThostFtdcInvestorPositionField)


class CThostFtdcPositionProfitAlgorithmField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    BrokerID = property(
        _ctp.CThostFtdcPositionProfitAlgorithmField_BrokerID_get,
        _ctp.CThostFtdcPositionProfitAlgorithmField_BrokerID_set,
    )
    AccountID = property(
        _ctp.CThostFtdcPositionProfitAlgorithmField_AccountID_get,
        _ctp.CThostFtdcPositionProfitAlgorithmField_AccountID_set,
    )
    Algorithm = property(
        _ctp.CThostFtdcPositionProfitAlgorithmField_Algorithm_get,
        _ctp.CThostFtdcPositionProfitAlgorithmField_Algorithm_set,
    )
    Memo = property(
        _ctp.CThostFtdcPositionProfitAlgorithmField_Memo_get,
        _ctp.CThostFtdcPositionProfitAlgorithmField_Memo_set,
    )
    CurrencyID = property(
        _ctp.CThostFtdcPositionProfitAlgorithmField_CurrencyID_get,
        _ctp.CThostFtdcPositionProfitAlgorithmField_CurrencyID_set,
    )

    def __init__(self):
        _ctp.CThostFtdcPositionProfitAlgorithmField_swiginit(
            self, _ctp.new_CThostFtdcPositionProfitAlgorithmField()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcPositionProfitAlgorithmField


# Register CThostFtdcPositionProfitAlgorithmField in _ctp:
_ctp.CThostFtdcPositionProfitAlgorithmField_swigregister(CThostFtdcPositionProfitAlgorithmField)


class CThostFtdcInvestorPositionDetailField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    reserve1 = property(
        _ctp.CThostFtdcInvestorPositionDetailField_reserve1_get,
        _ctp.CThostFtdcInvestorPositionDetailField_reserve1_set,
    )
    BrokerID = property(
        _ctp.CThostFtdcInvestorPositionDetailField_BrokerID_get,
        _ctp.CThostFtdcInvestorPositionDetailField_BrokerID_set,
    )
    InvestorID = property(
        _ctp.CThostFtdcInvestorPositionDetailField_InvestorID_get,
        _ctp.CThostFtdcInvestorPositionDetailField_InvestorID_set,
    )
    HedgeFlag = property(
        _ctp.CThostFtdcInvestorPositionDetailField_HedgeFlag_get,
        _ctp.CThostFtdcInvestorPositionDetailField_HedgeFlag_set,
    )
    Direction = property(
        _ctp.CThostFtdcInvestorPositionDetailField_Direction_get,
        _ctp.CThostFtdcInvestorPositionDetailField_Direction_set,
    )
    OpenDate = property(
        _ctp.CThostFtdcInvestorPositionDetailField_OpenDate_get,
        _ctp.CThostFtdcInvestorPositionDetailField_OpenDate_set,
    )
    TradeID = property(
        _ctp.CThostFtdcInvestorPositionDetailField_TradeID_get,
        _ctp.CThostFtdcInvestorPositionDetailField_TradeID_set,
    )
    Volume = property(
        _ctp.CThostFtdcInvestorPositionDetailField_Volume_get,
        _ctp.CThostFtdcInvestorPositionDetailField_Volume_set,
    )
    OpenPrice = property(
        _ctp.CThostFtdcInvestorPositionDetailField_OpenPrice_get,
        _ctp.CThostFtdcInvestorPositionDetailField_OpenPrice_set,
    )
    TradingDay = property(
        _ctp.CThostFtdcInvestorPositionDetailField_TradingDay_get,
        _ctp.CThostFtdcInvestorPositionDetailField_TradingDay_set,
    )
    SettlementID = property(
        _ctp.CThostFtdcInvestorPositionDetailField_SettlementID_get,
        _ctp.CThostFtdcInvestorPositionDetailField_SettlementID_set,
    )
    TradeType = property(
        _ctp.CThostFtdcInvestorPositionDetailField_TradeType_get,
        _ctp.CThostFtdcInvestorPositionDetailField_TradeType_set,
    )
    reserve2 = property(
        _ctp.CThostFtdcInvestorPositionDetailField_reserve2_get,
        _ctp.CThostFtdcInvestorPositionDetailField_reserve2_set,
    )
    ExchangeID = property(
        _ctp.CThostFtdcInvestorPositionDetailField_ExchangeID_get,
        _ctp.CThostFtdcInvestorPositionDetailField_ExchangeID_set,
    )
    CloseProfitByDate = property(
        _ctp.CThostFtdcInvestorPositionDetailField_CloseProfitByDate_get,
        _ctp.CThostFtdcInvestorPositionDetailField_CloseProfitByDate_set,
    )
    CloseProfitByTrade = property(
        _ctp.CThostFtdcInvestorPositionDetailField_CloseProfitByTrade_get,
        _ctp.CThostFtdcInvestorPositionDetailField_CloseProfitByTrade_set,
    )
    PositionProfitByDate = property(
        _ctp.CThostFtdcInvestorPositionDetailField_PositionProfitByDate_get,
        _ctp.CThostFtdcInvestorPositionDetailField_PositionProfitByDate_set,
    )
    PositionProfitByTrade = property(
        _ctp.CThostFtdcInvestorPositionDetailField_PositionProfitByTrade_get,
        _ctp.CThostFtdcInvestorPositionDetailField_PositionProfitByTrade_set,
    )
    Margin = property(
        _ctp.CThostFtdcInvestorPositionDetailField_Margin_get,
        _ctp.CThostFtdcInvestorPositionDetailField_Margin_set,
    )
    ExchMargin = property(
        _ctp.CThostFtdcInvestorPositionDetailField_ExchMargin_get,
        _ctp.CThostFtdcInvestorPositionDetailField_ExchMargin_set,
    )
    MarginRateByMoney = property(
        _ctp.CThostFtdcInvestorPositionDetailField_MarginRateByMoney_get,
        _ctp.CThostFtdcInvestorPositionDetailField_MarginRateByMoney_set,
    )
    MarginRateByVolume = property(
        _ctp.CThostFtdcInvestorPositionDetailField_MarginRateByVolume_get,
        _ctp.CThostFtdcInvestorPositionDetailField_MarginRateByVolume_set,
    )
    LastSettlementPrice = property(
        _ctp.CThostFtdcInvestorPositionDetailField_LastSettlementPrice_get,
        _ctp.CThostFtdcInvestorPositionDetailField_LastSettlementPrice_set,
    )
    SettlementPrice = property(
        _ctp.CThostFtdcInvestorPositionDetailField_SettlementPrice_get,
        _ctp.CThostFtdcInvestorPositionDetailField_SettlementPrice_set,
    )
    CloseVolume = property(
        _ctp.CThostFtdcInvestorPositionDetailField_CloseVolume_get,
        _ctp.CThostFtdcInvestorPositionDetailField_CloseVolume_set,
    )
    CloseAmount = property(
        _ctp.CThostFtdcInvestorPositionDetailField_CloseAmount_get,
        _ctp.CThostFtdcInvestorPositionDetailField_CloseAmount_set,
    )
    TimeFirstVolume = property(
        _ctp.CThostFtdcInvestorPositionDetailField_TimeFirstVolume_get,
        _ctp.CThostFtdcInvestorPositionDetailField_TimeFirstVolume_set,
    )
    InvestUnitID = property(
        _ctp.CThostFtdcInvestorPositionDetailField_InvestUnitID_get,
        _ctp.CThostFtdcInvestorPositionDetailField_InvestUnitID_set,
    )
    SpecPosiType = property(
        _ctp.CThostFtdcInvestorPositionDetailField_SpecPosiType_get,
        _ctp.CThostFtdcInvestorPositionDetailField_SpecPosiType_set,
    )
    InstrumentID = property(
        _ctp.CThostFtdcInvestorPositionDetailField_InstrumentID_get,
        _ctp.CThostFtdcInvestorPositionDetailField_InstrumentID_set,
    )
    CombInstrumentID = property(
        _ctp.CThostFtdcInvestorPositionDetailField_CombInstrumentID_get,
        _ctp.CThostFtdcInvestorPositionDetailField_CombInstrumentID_set,
    )

    def __init__(self):
        _ctp.CThostFtdcInvestorPositionDetailField_swiginit(
            self, _ctp.new_CThostFtdcInvestorPositionDetailField()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcInvestorPositionDetailField


# Register CThostFtdcInvestorPositionDetailField in _ctp:
_ctp.CThostFtdcInvestorPositionDetailField_swigregister(CThostFtdcInvestorPositionDetailField)


class CThostFtdcInvestorPositionCombineDetailField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    TradingDay = property(
        _ctp.CThostFtdcInvestorPositionCombineDetailField_TradingDay_get,
        _ctp.CThostFtdcInvestorPositionCombineDetailField_TradingDay_set,
    )
    OpenDate = property(
        _ctp.CThostFtdcInvestorPositionCombineDetailField_OpenDate_get,
        _ctp.CThostFtdcInvestorPositionCombineDetailField_OpenDate_set,
    )
    ExchangeID = property(
        _ctp.CThostFtdcInvestorPositionCombineDetailField_ExchangeID_get,
        _ctp.CThostFtdcInvestorPositionCombineDetailField_ExchangeID_set,
    )
    SettlementID = property(
        _ctp.CThostFtdcInvestorPositionCombineDetailField_SettlementID_get,
        _ctp.CThostFtdcInvestorPositionCombineDetailField_SettlementID_set,
    )
    BrokerID = property(
        _ctp.CThostFtdcInvestorPositionCombineDetailField_BrokerID_get,
        _ctp.CThostFtdcInvestorPositionCombineDetailField_BrokerID_set,
    )
    InvestorID = property(
        _ctp.CThostFtdcInvestorPositionCombineDetailField_InvestorID_get,
        _ctp.CThostFtdcInvestorPositionCombineDetailField_InvestorID_set,
    )
    ComTradeID = property(
        _ctp.CThostFtdcInvestorPositionCombineDetailField_ComTradeID_get,
        _ctp.CThostFtdcInvestorPositionCombineDetailField_ComTradeID_set,
    )
    TradeID = property(
        _ctp.CThostFtdcInvestorPositionCombineDetailField_TradeID_get,
        _ctp.CThostFtdcInvestorPositionCombineDetailField_TradeID_set,
    )
    reserve1 = property(
        _ctp.CThostFtdcInvestorPositionCombineDetailField_reserve1_get,
        _ctp.CThostFtdcInvestorPositionCombineDetailField_reserve1_set,
    )
    HedgeFlag = property(
        _ctp.CThostFtdcInvestorPositionCombineDetailField_HedgeFlag_get,
        _ctp.CThostFtdcInvestorPositionCombineDetailField_HedgeFlag_set,
    )
    Direction = property(
        _ctp.CThostFtdcInvestorPositionCombineDetailField_Direction_get,
        _ctp.CThostFtdcInvestorPositionCombineDetailField_Direction_set,
    )
    TotalAmt = property(
        _ctp.CThostFtdcInvestorPositionCombineDetailField_TotalAmt_get,
        _ctp.CThostFtdcInvestorPositionCombineDetailField_TotalAmt_set,
    )
    Margin = property(
        _ctp.CThostFtdcInvestorPositionCombineDetailField_Margin_get,
        _ctp.CThostFtdcInvestorPositionCombineDetailField_Margin_set,
    )
    ExchMargin = property(
        _ctp.CThostFtdcInvestorPositionCombineDetailField_ExchMargin_get,
        _ctp.CThostFtdcInvestorPositionCombineDetailField_ExchMargin_set,
    )
    MarginRateByMoney = property(
        _ctp.CThostFtdcInvestorPositionCombineDetailField_MarginRateByMoney_get,
        _ctp.CThostFtdcInvestorPositionCombineDetailField_MarginRateByMoney_set,
    )
    MarginRateByVolume = property(
        _ctp.CThostFtdcInvestorPositionCombineDetailField_MarginRateByVolume_get,
        _ctp.CThostFtdcInvestorPositionCombineDetailField_MarginRateByVolume_set,
    )
    LegID = property(
        _ctp.CThostFtdcInvestorPositionCombineDetailField_LegID_get,
        _ctp.CThostFtdcInvestorPositionCombineDetailField_LegID_set,
    )
    LegMultiple = property(
        _ctp.CThostFtdcInvestorPositionCombineDetailField_LegMultiple_get,
        _ctp.CThostFtdcInvestorPositionCombineDetailField_LegMultiple_set,
    )
    reserve2 = property(
        _ctp.CThostFtdcInvestorPositionCombineDetailField_reserve2_get,
        _ctp.CThostFtdcInvestorPositionCombineDetailField_reserve2_set,
    )
    TradeGroupID = property(
        _ctp.CThostFtdcInvestorPositionCombineDetailField_TradeGroupID_get,
        _ctp.CThostFtdcInvestorPositionCombineDetailField_TradeGroupID_set,
    )
    InvestUnitID = property(
        _ctp.CThostFtdcInvestorPositionCombineDetailField_InvestUnitID_get,
        _ctp.CThostFtdcInvestorPositionCombineDetailField_InvestUnitID_set,
    )
    InstrumentID = property(
        _ctp.CThostFtdcInvestorPositionCombineDetailField_InstrumentID_get,
        _ctp.CThostFtdcInvestorPositionCombineDetailField_InstrumentID_set,
    )
    CombInstrumentID = property(
        _ctp.CThostFtdcInvestorPositionCombineDetailField_CombInstrumentID_get,
        _ctp.CThostFtdcInvestorPositionCombineDetailField_CombInstrumentID_set,
    )

    def __init__(self):
        _ctp.CThostFtdcInvestorPositionCombineDetailField_swiginit(
            self, _ctp.new_CThostFtdcInvestorPositionCombineDetailField()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcInvestorPositionCombineDetailField


# Register CThostFtdcInvestorPositionCombineDetailField in _ctp:
_ctp.CThostFtdcInvestorPositionCombineDetailField_swigregister(
    CThostFtdcInvestorPositionCombineDetailField
)

__all__ = [
    "CThostFtdcInvestorPositionField",
    "CThostFtdcPositionProfitAlgorithmField",
    "CThostFtdcInvestorPositionDetailField",
    "CThostFtdcInvestorPositionCombineDetailField",
]
