# AUTO-GENERATED by split_ctp_wrapper.py — DO NOT EDIT
"""CTP 账户/资金相关结构"""

from __future__ import annotations

from ._ctp_base import _ctp, _swig_repr


class CThostFtdcTradingAccountField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    BrokerID = property(
        _ctp.CThostFtdcTradingAccountField_BrokerID_get,
        _ctp.CThostFtdcTradingAccountField_BrokerID_set,
    )
    AccountID = property(
        _ctp.CThostFtdcTradingAccountField_AccountID_get,
        _ctp.CThostFtdcTradingAccountField_AccountID_set,
    )
    PreMortgage = property(
        _ctp.CThostFtdcTradingAccountField_PreMortgage_get,
        _ctp.CThostFtdcTradingAccountField_PreMortgage_set,
    )
    PreCredit = property(
        _ctp.CThostFtdcTradingAccountField_PreCredit_get,
        _ctp.CThostFtdcTradingAccountField_PreCredit_set,
    )
    PreDeposit = property(
        _ctp.CThostFtdcTradingAccountField_PreDeposit_get,
        _ctp.CThostFtdcTradingAccountField_PreDeposit_set,
    )
    PreBalance = property(
        _ctp.CThostFtdcTradingAccountField_PreBalance_get,
        _ctp.CThostFtdcTradingAccountField_PreBalance_set,
    )
    PreMargin = property(
        _ctp.CThostFtdcTradingAccountField_PreMargin_get,
        _ctp.CThostFtdcTradingAccountField_PreMargin_set,
    )
    InterestBase = property(
        _ctp.CThostFtdcTradingAccountField_InterestBase_get,
        _ctp.CThostFtdcTradingAccountField_InterestBase_set,
    )
    Interest = property(
        _ctp.CThostFtdcTradingAccountField_Interest_get,
        _ctp.CThostFtdcTradingAccountField_Interest_set,
    )
    Deposit = property(
        _ctp.CThostFtdcTradingAccountField_Deposit_get,
        _ctp.CThostFtdcTradingAccountField_Deposit_set,
    )
    Withdraw = property(
        _ctp.CThostFtdcTradingAccountField_Withdraw_get,
        _ctp.CThostFtdcTradingAccountField_Withdraw_set,
    )
    FrozenMargin = property(
        _ctp.CThostFtdcTradingAccountField_FrozenMargin_get,
        _ctp.CThostFtdcTradingAccountField_FrozenMargin_set,
    )
    FrozenCash = property(
        _ctp.CThostFtdcTradingAccountField_FrozenCash_get,
        _ctp.CThostFtdcTradingAccountField_FrozenCash_set,
    )
    FrozenCommission = property(
        _ctp.CThostFtdcTradingAccountField_FrozenCommission_get,
        _ctp.CThostFtdcTradingAccountField_FrozenCommission_set,
    )
    CurrMargin = property(
        _ctp.CThostFtdcTradingAccountField_CurrMargin_get,
        _ctp.CThostFtdcTradingAccountField_CurrMargin_set,
    )
    CashIn = property(
        _ctp.CThostFtdcTradingAccountField_CashIn_get, _ctp.CThostFtdcTradingAccountField_CashIn_set
    )
    Commission = property(
        _ctp.CThostFtdcTradingAccountField_Commission_get,
        _ctp.CThostFtdcTradingAccountField_Commission_set,
    )
    CloseProfit = property(
        _ctp.CThostFtdcTradingAccountField_CloseProfit_get,
        _ctp.CThostFtdcTradingAccountField_CloseProfit_set,
    )
    PositionProfit = property(
        _ctp.CThostFtdcTradingAccountField_PositionProfit_get,
        _ctp.CThostFtdcTradingAccountField_PositionProfit_set,
    )
    Balance = property(
        _ctp.CThostFtdcTradingAccountField_Balance_get,
        _ctp.CThostFtdcTradingAccountField_Balance_set,
    )
    Available = property(
        _ctp.CThostFtdcTradingAccountField_Available_get,
        _ctp.CThostFtdcTradingAccountField_Available_set,
    )
    WithdrawQuota = property(
        _ctp.CThostFtdcTradingAccountField_WithdrawQuota_get,
        _ctp.CThostFtdcTradingAccountField_WithdrawQuota_set,
    )
    Reserve = property(
        _ctp.CThostFtdcTradingAccountField_Reserve_get,
        _ctp.CThostFtdcTradingAccountField_Reserve_set,
    )
    TradingDay = property(
        _ctp.CThostFtdcTradingAccountField_TradingDay_get,
        _ctp.CThostFtdcTradingAccountField_TradingDay_set,
    )
    SettlementID = property(
        _ctp.CThostFtdcTradingAccountField_SettlementID_get,
        _ctp.CThostFtdcTradingAccountField_SettlementID_set,
    )
    Credit = property(
        _ctp.CThostFtdcTradingAccountField_Credit_get, _ctp.CThostFtdcTradingAccountField_Credit_set
    )
    Mortgage = property(
        _ctp.CThostFtdcTradingAccountField_Mortgage_get,
        _ctp.CThostFtdcTradingAccountField_Mortgage_set,
    )
    ExchangeMargin = property(
        _ctp.CThostFtdcTradingAccountField_ExchangeMargin_get,
        _ctp.CThostFtdcTradingAccountField_ExchangeMargin_set,
    )
    DeliveryMargin = property(
        _ctp.CThostFtdcTradingAccountField_DeliveryMargin_get,
        _ctp.CThostFtdcTradingAccountField_DeliveryMargin_set,
    )
    ExchangeDeliveryMargin = property(
        _ctp.CThostFtdcTradingAccountField_ExchangeDeliveryMargin_get,
        _ctp.CThostFtdcTradingAccountField_ExchangeDeliveryMargin_set,
    )
    ReserveBalance = property(
        _ctp.CThostFtdcTradingAccountField_ReserveBalance_get,
        _ctp.CThostFtdcTradingAccountField_ReserveBalance_set,
    )
    CurrencyID = property(
        _ctp.CThostFtdcTradingAccountField_CurrencyID_get,
        _ctp.CThostFtdcTradingAccountField_CurrencyID_set,
    )
    PreFundMortgageIn = property(
        _ctp.CThostFtdcTradingAccountField_PreFundMortgageIn_get,
        _ctp.CThostFtdcTradingAccountField_PreFundMortgageIn_set,
    )
    PreFundMortgageOut = property(
        _ctp.CThostFtdcTradingAccountField_PreFundMortgageOut_get,
        _ctp.CThostFtdcTradingAccountField_PreFundMortgageOut_set,
    )
    FundMortgageIn = property(
        _ctp.CThostFtdcTradingAccountField_FundMortgageIn_get,
        _ctp.CThostFtdcTradingAccountField_FundMortgageIn_set,
    )
    FundMortgageOut = property(
        _ctp.CThostFtdcTradingAccountField_FundMortgageOut_get,
        _ctp.CThostFtdcTradingAccountField_FundMortgageOut_set,
    )
    FundMortgageAvailable = property(
        _ctp.CThostFtdcTradingAccountField_FundMortgageAvailable_get,
        _ctp.CThostFtdcTradingAccountField_FundMortgageAvailable_set,
    )
    MortgageableFund = property(
        _ctp.CThostFtdcTradingAccountField_MortgageableFund_get,
        _ctp.CThostFtdcTradingAccountField_MortgageableFund_set,
    )
    SpecProductMargin = property(
        _ctp.CThostFtdcTradingAccountField_SpecProductMargin_get,
        _ctp.CThostFtdcTradingAccountField_SpecProductMargin_set,
    )
    SpecProductFrozenMargin = property(
        _ctp.CThostFtdcTradingAccountField_SpecProductFrozenMargin_get,
        _ctp.CThostFtdcTradingAccountField_SpecProductFrozenMargin_set,
    )
    SpecProductCommission = property(
        _ctp.CThostFtdcTradingAccountField_SpecProductCommission_get,
        _ctp.CThostFtdcTradingAccountField_SpecProductCommission_set,
    )
    SpecProductFrozenCommission = property(
        _ctp.CThostFtdcTradingAccountField_SpecProductFrozenCommission_get,
        _ctp.CThostFtdcTradingAccountField_SpecProductFrozenCommission_set,
    )
    SpecProductPositionProfit = property(
        _ctp.CThostFtdcTradingAccountField_SpecProductPositionProfit_get,
        _ctp.CThostFtdcTradingAccountField_SpecProductPositionProfit_set,
    )
    SpecProductCloseProfit = property(
        _ctp.CThostFtdcTradingAccountField_SpecProductCloseProfit_get,
        _ctp.CThostFtdcTradingAccountField_SpecProductCloseProfit_set,
    )
    SpecProductPositionProfitByAlg = property(
        _ctp.CThostFtdcTradingAccountField_SpecProductPositionProfitByAlg_get,
        _ctp.CThostFtdcTradingAccountField_SpecProductPositionProfitByAlg_set,
    )
    SpecProductExchangeMargin = property(
        _ctp.CThostFtdcTradingAccountField_SpecProductExchangeMargin_get,
        _ctp.CThostFtdcTradingAccountField_SpecProductExchangeMargin_set,
    )
    BizType = property(
        _ctp.CThostFtdcTradingAccountField_BizType_get,
        _ctp.CThostFtdcTradingAccountField_BizType_set,
    )
    FrozenSwap = property(
        _ctp.CThostFtdcTradingAccountField_FrozenSwap_get,
        _ctp.CThostFtdcTradingAccountField_FrozenSwap_set,
    )
    RemainSwap = property(
        _ctp.CThostFtdcTradingAccountField_RemainSwap_get,
        _ctp.CThostFtdcTradingAccountField_RemainSwap_set,
    )

    def __init__(self):
        _ctp.CThostFtdcTradingAccountField_swiginit(self, _ctp.new_CThostFtdcTradingAccountField())

    __swig_destroy__ = _ctp.delete_CThostFtdcTradingAccountField


# Register CThostFtdcTradingAccountField in _ctp:
_ctp.CThostFtdcTradingAccountField_swigregister(CThostFtdcTradingAccountField)


class CThostFtdcSyncDepositField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    DepositSeqNo = property(
        _ctp.CThostFtdcSyncDepositField_DepositSeqNo_get,
        _ctp.CThostFtdcSyncDepositField_DepositSeqNo_set,
    )
    BrokerID = property(
        _ctp.CThostFtdcSyncDepositField_BrokerID_get, _ctp.CThostFtdcSyncDepositField_BrokerID_set
    )
    InvestorID = property(
        _ctp.CThostFtdcSyncDepositField_InvestorID_get,
        _ctp.CThostFtdcSyncDepositField_InvestorID_set,
    )
    Deposit = property(
        _ctp.CThostFtdcSyncDepositField_Deposit_get, _ctp.CThostFtdcSyncDepositField_Deposit_set
    )
    IsForce = property(
        _ctp.CThostFtdcSyncDepositField_IsForce_get, _ctp.CThostFtdcSyncDepositField_IsForce_set
    )
    CurrencyID = property(
        _ctp.CThostFtdcSyncDepositField_CurrencyID_get,
        _ctp.CThostFtdcSyncDepositField_CurrencyID_set,
    )
    IsFromSopt = property(
        _ctp.CThostFtdcSyncDepositField_IsFromSopt_get,
        _ctp.CThostFtdcSyncDepositField_IsFromSopt_set,
    )
    TradingPassword = property(
        _ctp.CThostFtdcSyncDepositField_TradingPassword_get,
        _ctp.CThostFtdcSyncDepositField_TradingPassword_set,
    )
    IsSecAgentTranfer = property(
        _ctp.CThostFtdcSyncDepositField_IsSecAgentTranfer_get,
        _ctp.CThostFtdcSyncDepositField_IsSecAgentTranfer_set,
    )

    def __init__(self):
        _ctp.CThostFtdcSyncDepositField_swiginit(self, _ctp.new_CThostFtdcSyncDepositField())

    __swig_destroy__ = _ctp.delete_CThostFtdcSyncDepositField


# Register CThostFtdcSyncDepositField in _ctp:
_ctp.CThostFtdcSyncDepositField_swigregister(CThostFtdcSyncDepositField)


class CThostFtdcSyncFundMortgageField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    MortgageSeqNo = property(
        _ctp.CThostFtdcSyncFundMortgageField_MortgageSeqNo_get,
        _ctp.CThostFtdcSyncFundMortgageField_MortgageSeqNo_set,
    )
    BrokerID = property(
        _ctp.CThostFtdcSyncFundMortgageField_BrokerID_get,
        _ctp.CThostFtdcSyncFundMortgageField_BrokerID_set,
    )
    InvestorID = property(
        _ctp.CThostFtdcSyncFundMortgageField_InvestorID_get,
        _ctp.CThostFtdcSyncFundMortgageField_InvestorID_set,
    )
    FromCurrencyID = property(
        _ctp.CThostFtdcSyncFundMortgageField_FromCurrencyID_get,
        _ctp.CThostFtdcSyncFundMortgageField_FromCurrencyID_set,
    )
    MortgageAmount = property(
        _ctp.CThostFtdcSyncFundMortgageField_MortgageAmount_get,
        _ctp.CThostFtdcSyncFundMortgageField_MortgageAmount_set,
    )
    ToCurrencyID = property(
        _ctp.CThostFtdcSyncFundMortgageField_ToCurrencyID_get,
        _ctp.CThostFtdcSyncFundMortgageField_ToCurrencyID_set,
    )

    def __init__(self):
        _ctp.CThostFtdcSyncFundMortgageField_swiginit(
            self, _ctp.new_CThostFtdcSyncFundMortgageField()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcSyncFundMortgageField


# Register CThostFtdcSyncFundMortgageField in _ctp:
_ctp.CThostFtdcSyncFundMortgageField_swigregister(CThostFtdcSyncFundMortgageField)


class CThostFtdcSyncDelaySwapField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    DelaySwapSeqNo = property(
        _ctp.CThostFtdcSyncDelaySwapField_DelaySwapSeqNo_get,
        _ctp.CThostFtdcSyncDelaySwapField_DelaySwapSeqNo_set,
    )
    BrokerID = property(
        _ctp.CThostFtdcSyncDelaySwapField_BrokerID_get,
        _ctp.CThostFtdcSyncDelaySwapField_BrokerID_set,
    )
    InvestorID = property(
        _ctp.CThostFtdcSyncDelaySwapField_InvestorID_get,
        _ctp.CThostFtdcSyncDelaySwapField_InvestorID_set,
    )
    FromCurrencyID = property(
        _ctp.CThostFtdcSyncDelaySwapField_FromCurrencyID_get,
        _ctp.CThostFtdcSyncDelaySwapField_FromCurrencyID_set,
    )
    FromAmount = property(
        _ctp.CThostFtdcSyncDelaySwapField_FromAmount_get,
        _ctp.CThostFtdcSyncDelaySwapField_FromAmount_set,
    )
    FromFrozenSwap = property(
        _ctp.CThostFtdcSyncDelaySwapField_FromFrozenSwap_get,
        _ctp.CThostFtdcSyncDelaySwapField_FromFrozenSwap_set,
    )
    FromRemainSwap = property(
        _ctp.CThostFtdcSyncDelaySwapField_FromRemainSwap_get,
        _ctp.CThostFtdcSyncDelaySwapField_FromRemainSwap_set,
    )
    ToCurrencyID = property(
        _ctp.CThostFtdcSyncDelaySwapField_ToCurrencyID_get,
        _ctp.CThostFtdcSyncDelaySwapField_ToCurrencyID_set,
    )
    ToAmount = property(
        _ctp.CThostFtdcSyncDelaySwapField_ToAmount_get,
        _ctp.CThostFtdcSyncDelaySwapField_ToAmount_set,
    )
    IsManualSwap = property(
        _ctp.CThostFtdcSyncDelaySwapField_IsManualSwap_get,
        _ctp.CThostFtdcSyncDelaySwapField_IsManualSwap_set,
    )
    IsAllRemainSetZero = property(
        _ctp.CThostFtdcSyncDelaySwapField_IsAllRemainSetZero_get,
        _ctp.CThostFtdcSyncDelaySwapField_IsAllRemainSetZero_set,
    )

    def __init__(self):
        _ctp.CThostFtdcSyncDelaySwapField_swiginit(self, _ctp.new_CThostFtdcSyncDelaySwapField())

    __swig_destroy__ = _ctp.delete_CThostFtdcSyncDelaySwapField


# Register CThostFtdcSyncDelaySwapField in _ctp:
_ctp.CThostFtdcSyncDelaySwapField_swigregister(CThostFtdcSyncDelaySwapField)


class CThostFtdcTradingAccountPasswordField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    BrokerID = property(
        _ctp.CThostFtdcTradingAccountPasswordField_BrokerID_get,
        _ctp.CThostFtdcTradingAccountPasswordField_BrokerID_set,
    )
    AccountID = property(
        _ctp.CThostFtdcTradingAccountPasswordField_AccountID_get,
        _ctp.CThostFtdcTradingAccountPasswordField_AccountID_set,
    )
    Password = property(
        _ctp.CThostFtdcTradingAccountPasswordField_Password_get,
        _ctp.CThostFtdcTradingAccountPasswordField_Password_set,
    )
    CurrencyID = property(
        _ctp.CThostFtdcTradingAccountPasswordField_CurrencyID_get,
        _ctp.CThostFtdcTradingAccountPasswordField_CurrencyID_set,
    )

    def __init__(self):
        _ctp.CThostFtdcTradingAccountPasswordField_swiginit(
            self, _ctp.new_CThostFtdcTradingAccountPasswordField()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcTradingAccountPasswordField


# Register CThostFtdcTradingAccountPasswordField in _ctp:
_ctp.CThostFtdcTradingAccountPasswordField_swigregister(CThostFtdcTradingAccountPasswordField)


class CThostFtdcTradingAccountPasswordUpdateV1Field:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    BrokerID = property(
        _ctp.CThostFtdcTradingAccountPasswordUpdateV1Field_BrokerID_get,
        _ctp.CThostFtdcTradingAccountPasswordUpdateV1Field_BrokerID_set,
    )
    InvestorID = property(
        _ctp.CThostFtdcTradingAccountPasswordUpdateV1Field_InvestorID_get,
        _ctp.CThostFtdcTradingAccountPasswordUpdateV1Field_InvestorID_set,
    )
    OldPassword = property(
        _ctp.CThostFtdcTradingAccountPasswordUpdateV1Field_OldPassword_get,
        _ctp.CThostFtdcTradingAccountPasswordUpdateV1Field_OldPassword_set,
    )
    NewPassword = property(
        _ctp.CThostFtdcTradingAccountPasswordUpdateV1Field_NewPassword_get,
        _ctp.CThostFtdcTradingAccountPasswordUpdateV1Field_NewPassword_set,
    )

    def __init__(self):
        _ctp.CThostFtdcTradingAccountPasswordUpdateV1Field_swiginit(
            self, _ctp.new_CThostFtdcTradingAccountPasswordUpdateV1Field()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcTradingAccountPasswordUpdateV1Field


# Register CThostFtdcTradingAccountPasswordUpdateV1Field in _ctp:
_ctp.CThostFtdcTradingAccountPasswordUpdateV1Field_swigregister(
    CThostFtdcTradingAccountPasswordUpdateV1Field
)


class CThostFtdcTradingAccountPasswordUpdateField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    BrokerID = property(
        _ctp.CThostFtdcTradingAccountPasswordUpdateField_BrokerID_get,
        _ctp.CThostFtdcTradingAccountPasswordUpdateField_BrokerID_set,
    )
    AccountID = property(
        _ctp.CThostFtdcTradingAccountPasswordUpdateField_AccountID_get,
        _ctp.CThostFtdcTradingAccountPasswordUpdateField_AccountID_set,
    )
    OldPassword = property(
        _ctp.CThostFtdcTradingAccountPasswordUpdateField_OldPassword_get,
        _ctp.CThostFtdcTradingAccountPasswordUpdateField_OldPassword_set,
    )
    NewPassword = property(
        _ctp.CThostFtdcTradingAccountPasswordUpdateField_NewPassword_get,
        _ctp.CThostFtdcTradingAccountPasswordUpdateField_NewPassword_set,
    )
    CurrencyID = property(
        _ctp.CThostFtdcTradingAccountPasswordUpdateField_CurrencyID_get,
        _ctp.CThostFtdcTradingAccountPasswordUpdateField_CurrencyID_set,
    )

    def __init__(self):
        _ctp.CThostFtdcTradingAccountPasswordUpdateField_swiginit(
            self, _ctp.new_CThostFtdcTradingAccountPasswordUpdateField()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcTradingAccountPasswordUpdateField


# Register CThostFtdcTradingAccountPasswordUpdateField in _ctp:
_ctp.CThostFtdcTradingAccountPasswordUpdateField_swigregister(
    CThostFtdcTradingAccountPasswordUpdateField
)


class CThostFtdcTradingAccountReserveField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    BrokerID = property(
        _ctp.CThostFtdcTradingAccountReserveField_BrokerID_get,
        _ctp.CThostFtdcTradingAccountReserveField_BrokerID_set,
    )
    AccountID = property(
        _ctp.CThostFtdcTradingAccountReserveField_AccountID_get,
        _ctp.CThostFtdcTradingAccountReserveField_AccountID_set,
    )
    Reserve = property(
        _ctp.CThostFtdcTradingAccountReserveField_Reserve_get,
        _ctp.CThostFtdcTradingAccountReserveField_Reserve_set,
    )
    CurrencyID = property(
        _ctp.CThostFtdcTradingAccountReserveField_CurrencyID_get,
        _ctp.CThostFtdcTradingAccountReserveField_CurrencyID_set,
    )

    def __init__(self):
        _ctp.CThostFtdcTradingAccountReserveField_swiginit(
            self, _ctp.new_CThostFtdcTradingAccountReserveField()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcTradingAccountReserveField


# Register CThostFtdcTradingAccountReserveField in _ctp:
_ctp.CThostFtdcTradingAccountReserveField_swigregister(CThostFtdcTradingAccountReserveField)


class CThostFtdcSyncDelaySwapFrozenField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    DelaySwapSeqNo = property(
        _ctp.CThostFtdcSyncDelaySwapFrozenField_DelaySwapSeqNo_get,
        _ctp.CThostFtdcSyncDelaySwapFrozenField_DelaySwapSeqNo_set,
    )
    BrokerID = property(
        _ctp.CThostFtdcSyncDelaySwapFrozenField_BrokerID_get,
        _ctp.CThostFtdcSyncDelaySwapFrozenField_BrokerID_set,
    )
    InvestorID = property(
        _ctp.CThostFtdcSyncDelaySwapFrozenField_InvestorID_get,
        _ctp.CThostFtdcSyncDelaySwapFrozenField_InvestorID_set,
    )
    FromCurrencyID = property(
        _ctp.CThostFtdcSyncDelaySwapFrozenField_FromCurrencyID_get,
        _ctp.CThostFtdcSyncDelaySwapFrozenField_FromCurrencyID_set,
    )
    FromRemainSwap = property(
        _ctp.CThostFtdcSyncDelaySwapFrozenField_FromRemainSwap_get,
        _ctp.CThostFtdcSyncDelaySwapFrozenField_FromRemainSwap_set,
    )
    IsManualSwap = property(
        _ctp.CThostFtdcSyncDelaySwapFrozenField_IsManualSwap_get,
        _ctp.CThostFtdcSyncDelaySwapFrozenField_IsManualSwap_set,
    )

    def __init__(self):
        _ctp.CThostFtdcSyncDelaySwapFrozenField_swiginit(
            self, _ctp.new_CThostFtdcSyncDelaySwapFrozenField()
        )

    __swig_destroy__ = _ctp.delete_CThostFtdcSyncDelaySwapFrozenField


# Register CThostFtdcSyncDelaySwapFrozenField in _ctp:
_ctp.CThostFtdcSyncDelaySwapFrozenField_swigregister(CThostFtdcSyncDelaySwapFrozenField)

__all__ = [
    "CThostFtdcTradingAccountField",
    "CThostFtdcSyncDepositField",
    "CThostFtdcSyncFundMortgageField",
    "CThostFtdcSyncDelaySwapField",
    "CThostFtdcTradingAccountPasswordField",
    "CThostFtdcTradingAccountPasswordUpdateV1Field",
    "CThostFtdcTradingAccountPasswordUpdateField",
    "CThostFtdcTradingAccountReserveField",
    "CThostFtdcSyncDelaySwapFrozenField",
]
