# AUTO-GENERATED by split_ctp_wrapper.py — DO NOT EDIT
"""CTP 成交相关结构"""

from __future__ import annotations

from ._ctp_base import _ctp, _swig_repr


class CThostFtdcTradeField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    BrokerID = property(
        _ctp.CThostFtdcTradeField_BrokerID_get, _ctp.CThostFtdcTradeField_BrokerID_set
    )
    InvestorID = property(
        _ctp.CThostFtdcTradeField_InvestorID_get, _ctp.CThostFtdcTradeField_InvestorID_set
    )
    reserve1 = property(
        _ctp.CThostFtdcTradeField_reserve1_get, _ctp.CThostFtdcTradeField_reserve1_set
    )
    OrderRef = property(
        _ctp.CThostFtdcTradeField_OrderRef_get, _ctp.CThostFtdcTradeField_OrderRef_set
    )
    UserID = property(_ctp.CThostFtdcTradeField_UserID_get, _ctp.CThostFtdcTradeField_UserID_set)
    ExchangeID = property(
        _ctp.CThostFtdcTradeField_ExchangeID_get, _ctp.CThostFtdcTradeField_ExchangeID_set
    )
    TradeID = property(_ctp.CThostFtdcTradeField_TradeID_get, _ctp.CThostFtdcTradeField_TradeID_set)
    Direction = property(
        _ctp.CThostFtdcTradeField_Direction_get, _ctp.CThostFtdcTradeField_Direction_set
    )
    OrderSysID = property(
        _ctp.CThostFtdcTradeField_OrderSysID_get, _ctp.CThostFtdcTradeField_OrderSysID_set
    )
    ParticipantID = property(
        _ctp.CThostFtdcTradeField_ParticipantID_get, _ctp.CThostFtdcTradeField_ParticipantID_set
    )
    ClientID = property(
        _ctp.CThostFtdcTradeField_ClientID_get, _ctp.CThostFtdcTradeField_ClientID_set
    )
    TradingRole = property(
        _ctp.CThostFtdcTradeField_TradingRole_get, _ctp.CThostFtdcTradeField_TradingRole_set
    )
    reserve2 = property(
        _ctp.CThostFtdcTradeField_reserve2_get, _ctp.CThostFtdcTradeField_reserve2_set
    )
    OffsetFlag = property(
        _ctp.CThostFtdcTradeField_OffsetFlag_get, _ctp.CThostFtdcTradeField_OffsetFlag_set
    )
    HedgeFlag = property(
        _ctp.CThostFtdcTradeField_HedgeFlag_get, _ctp.CThostFtdcTradeField_HedgeFlag_set
    )
    Price = property(_ctp.CThostFtdcTradeField_Price_get, _ctp.CThostFtdcTradeField_Price_set)
    Volume = property(_ctp.CThostFtdcTradeField_Volume_get, _ctp.CThostFtdcTradeField_Volume_set)
    TradeDate = property(
        _ctp.CThostFtdcTradeField_TradeDate_get, _ctp.CThostFtdcTradeField_TradeDate_set
    )
    TradeTime = property(
        _ctp.CThostFtdcTradeField_TradeTime_get, _ctp.CThostFtdcTradeField_TradeTime_set
    )
    TradeType = property(
        _ctp.CThostFtdcTradeField_TradeType_get, _ctp.CThostFtdcTradeField_TradeType_set
    )
    PriceSource = property(
        _ctp.CThostFtdcTradeField_PriceSource_get, _ctp.CThostFtdcTradeField_PriceSource_set
    )
    TraderID = property(
        _ctp.CThostFtdcTradeField_TraderID_get, _ctp.CThostFtdcTradeField_TraderID_set
    )
    OrderLocalID = property(
        _ctp.CThostFtdcTradeField_OrderLocalID_get, _ctp.CThostFtdcTradeField_OrderLocalID_set
    )
    ClearingPartID = property(
        _ctp.CThostFtdcTradeField_ClearingPartID_get, _ctp.CThostFtdcTradeField_ClearingPartID_set
    )
    BusinessUnit = property(
        _ctp.CThostFtdcTradeField_BusinessUnit_get, _ctp.CThostFtdcTradeField_BusinessUnit_set
    )
    SequenceNo = property(
        _ctp.CThostFtdcTradeField_SequenceNo_get, _ctp.CThostFtdcTradeField_SequenceNo_set
    )
    TradingDay = property(
        _ctp.CThostFtdcTradeField_TradingDay_get, _ctp.CThostFtdcTradeField_TradingDay_set
    )
    SettlementID = property(
        _ctp.CThostFtdcTradeField_SettlementID_get, _ctp.CThostFtdcTradeField_SettlementID_set
    )
    BrokerOrderSeq = property(
        _ctp.CThostFtdcTradeField_BrokerOrderSeq_get, _ctp.CThostFtdcTradeField_BrokerOrderSeq_set
    )
    TradeSource = property(
        _ctp.CThostFtdcTradeField_TradeSource_get, _ctp.CThostFtdcTradeField_TradeSource_set
    )
    InvestUnitID = property(
        _ctp.CThostFtdcTradeField_InvestUnitID_get, _ctp.CThostFtdcTradeField_InvestUnitID_set
    )
    InstrumentID = property(
        _ctp.CThostFtdcTradeField_InstrumentID_get, _ctp.CThostFtdcTradeField_InstrumentID_set
    )
    ExchangeInstID = property(
        _ctp.CThostFtdcTradeField_ExchangeInstID_get, _ctp.CThostFtdcTradeField_ExchangeInstID_set
    )

    def __init__(self):
        _ctp.CThostFtdcTradeField_swiginit(self, _ctp.new_CThostFtdcTradeField())

    __swig_destroy__ = _ctp.delete_CThostFtdcTradeField


# Register CThostFtdcTradeField in _ctp:
_ctp.CThostFtdcTradeField_swigregister(CThostFtdcTradeField)


class CThostFtdcTradeParamField:
    thisown = property(
        lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag"
    )
    __repr__ = _swig_repr
    BrokerID = property(
        _ctp.CThostFtdcTradeParamField_BrokerID_get, _ctp.CThostFtdcTradeParamField_BrokerID_set
    )
    TradeParamID = property(
        _ctp.CThostFtdcTradeParamField_TradeParamID_get,
        _ctp.CThostFtdcTradeParamField_TradeParamID_set,
    )
    TradeParamValue = property(
        _ctp.CThostFtdcTradeParamField_TradeParamValue_get,
        _ctp.CThostFtdcTradeParamField_TradeParamValue_set,
    )
    Memo = property(
        _ctp.CThostFtdcTradeParamField_Memo_get, _ctp.CThostFtdcTradeParamField_Memo_set
    )

    def __init__(self):
        _ctp.CThostFtdcTradeParamField_swiginit(self, _ctp.new_CThostFtdcTradeParamField())

    __swig_destroy__ = _ctp.delete_CThostFtdcTradeParamField


# Register CThostFtdcTradeParamField in _ctp:
_ctp.CThostFtdcTradeParamField_swigregister(CThostFtdcTradeParamField)

__all__ = [
    "CThostFtdcTradeField",
    "CThostFtdcTradeParamField",
]
