@echo off
:: 安装 requirements.txt 中的依赖
:: pip install -U -r requirements.txt
SET BUILD_DIR=build
SET EGG_INFO_DIR=bt_api_py.egg-info
SET BENCHMARKS_DIR=.benchmarks
:: 切换到上一级目录
cd ..

:: 安装 bt_api_py 包
pip install -U --no-build-isolation ./bt_api_py

cd ./bt_api_py
:: 运行 backtrader 的测试用例，使用 4 个进程并行测试
:: pytest ./bt_api_py/tests -n 4
:: Delete intermediate build and egg-info directories
echo Deleting intermediate files...
IF EXIST %BUILD_DIR% (
    rmdir /s /q %BUILD_DIR%
    echo Deleted %BUILD_DIR% directory.
)
IF EXIST %EGG_INFO_DIR% (
    rmdir /s /q %EGG_INFO_DIR%
    echo Deleted %EGG_INFO_DIR% directory.
)
:: Delete the .benchmarks directory generated by pytest
IF EXIST %BENCHMARKS_DIR% (
    rmdir /s /q %BENCHMARKS_DIR%
    echo Deleted %BENCHMARKS_DIR% directory.
)

:: Delete all .log files
echo Deleting all .log files...
del /s /q *.log
echo All .log files deleted.
:: 暂停脚本，以便查看输出结果
:: pause