id: pancakeswap
display_name: PancakeSwap
venue_type: dex
website: https://pancakeswap.finance
api_doc: https://docs.pancakeswap.finance
base_urls:
  rest:
    default: https://proxy-worker-api.pancakeswap.com/bsc-exchange
    spot: https://proxy-worker-api.pancakeswap.com/bsc-exchange
  wss:
    default: wss://bsc-dataseed.binance.org
    spot: wss://bsc-dataseed.binance.org
authentication:
  type: none
kline_periods:
  1m: 1m
  5m: 5m
  15m: 15m
  30m: 30m
  1h: 1h
  4h: 4h
  1d: 1d
legal_currency: &id001
- USDT
- USD
- BNB
- BTC
- ETH
rate_limits:
- name: public_api
  type: fixed_window
  interval: 60
  limit: 60
  scope: global
asset_types:
  spot:
    exchange_name: pancakeswapSpot
    symbol_format: '{base}{quote}'
    rest_paths:
      get_server_time: GET /server_time
      get_tick: GET /ticker
      get_depth: GET /depth
      get_kline: GET /kline
    wss_paths:
      tick: '{symbol}@ticker'
    legal_currency: *id001
connection:
  type: http
  timeout: 10
  max_retries: 3
