#!/usr/bin/env python3
"""Isolated, artifact-first validation for BtApi plugin submodules.

The validator deliberately does not share an editable install or interpreter
between plugins.  Each package receives a fresh virtual environment, while a
base-package wheel is built once and installed into every environment.  Every
phase writes stdout/stderr to the artifact directory so a scheduled diagnostic
run remains useful even when many submodules are unavailable.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
import tomllib
import xml.etree.ElementTree as ET
from collections.abc import Iterable
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

DEFAULT_TIMEOUT_SECONDS = 300
TEST_TIMEOUT_SECONDS = 600
OFFLINE_TEST_MARKER_EXPRESSION = "not network and not integration and not performance and not e2e"


@dataclass
class PhaseResult:
    status: str  # passed | failed | skipped | timeout | unavailable
    exit_code: int | None
    duration_seconds: float
    stdout_path: str
    stderr_path: str
    classification: str = ""
    detail: str = ""


@dataclass
class PackageResult:
    package: str
    profile: str
    package_path: str
    status: str
    phases: dict[str, PhaseResult] = field(default_factory=dict)
    environment: dict[str, str] = field(default_factory=dict)
    classification: str = ""


def utc_now() -> str:
    return datetime.now(UTC).isoformat()


def load_toml(path: Path) -> dict[str, Any]:
    with path.open("rb") as handle:
        return tomllib.load(handle)


def package_names_for_profile(
    profile: str, config: dict[str, Any], bundle_catalog: dict[str, Any], repository_root: Path
) -> list[str]:
    """Resolve a validation profile without treating availability as success."""
    profiles = dict(config.get("profiles") or {})
    if profile not in profiles:
        raise ValueError(f"unknown validation profile: {profile}")
    seen: set[str] = set()
    names: list[str] = []

    def add(name: str) -> None:
        if name and name not in seen:
            seen.add(name)
            names.append(name)

    def visit(name: str) -> None:
        settings = dict(profiles[name])
        for child in settings.get("include_profiles", []):
            visit(str(child))
        if settings.get("include_base"):
            add("bt_api_base")
        bundle_name = settings.get("bundle")
        if bundle_name:
            bundle = dict((bundle_catalog.get("bundles") or {}).get(str(bundle_name)) or {})
            for venue in bundle.get("venues", []):
                add(str(venue.get("package") or ""))
        for package in settings.get("packages", []):
            add(str(package))
        if settings.get("discover_submodules"):
            submodule_root = repository_root / "bt_api"
            if submodule_root.exists():
                for candidate in sorted(submodule_root.glob("bt_api_*")):
                    add(candidate.name)

    visit(profile)
    return names


def _relative(path: Path, artifacts_dir: Path) -> str:
    return str(path.relative_to(artifacts_dir))


def _write_log(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _phase_paths(artifacts_dir: Path, package: str, phase: str) -> tuple[Path, Path]:
    base = artifacts_dir / "logs" / package
    return base / f"{phase}.stdout.log", base / f"{phase}.stderr.log"


def run_phase(
    *,
    command: list[str],
    cwd: Path,
    artifacts_dir: Path,
    package: str,
    phase: str,
    timeout_seconds: int,
    environment: dict[str, str] | None = None,
) -> PhaseResult:
    """Run one phase and persist both streams even when it fails or times out."""
    stdout_path, stderr_path = _phase_paths(artifacts_dir, package, phase)
    started = time.monotonic()
    env = os.environ.copy()
    if environment:
        env.update(environment)
    try:
        completed = subprocess.run(  # noqa: S603 - command is generated by this local validator
            command,
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
            check=False,
            env=env,
        )
    except subprocess.TimeoutExpired as exc:
        stdout = exc.stdout if isinstance(exc.stdout, str) else ""
        stderr = exc.stderr if isinstance(exc.stderr, str) else ""
        _write_log(stdout_path, stdout)
        _write_log(stderr_path, stderr)
        return PhaseResult(
            status="timeout",
            exit_code=None,
            duration_seconds=time.monotonic() - started,
            stdout_path=_relative(stdout_path, artifacts_dir),
            stderr_path=_relative(stderr_path, artifacts_dir),
            classification="timeout",
            detail=f"command exceeded {timeout_seconds}s",
        )
    _write_log(stdout_path, completed.stdout)
    _write_log(stderr_path, completed.stderr)
    return PhaseResult(
        status="passed" if completed.returncode == 0 else "failed",
        exit_code=completed.returncode,
        duration_seconds=time.monotonic() - started,
        stdout_path=_relative(stdout_path, artifacts_dir),
        stderr_path=_relative(stderr_path, artifacts_dir),
        classification="" if completed.returncode == 0 else phase,
        detail="" if completed.returncode == 0 else f"exit code {completed.returncode}",
    )


def unavailable_phase(artifacts_dir: Path, package: str, phase: str, detail: str) -> PhaseResult:
    stdout_path, stderr_path = _phase_paths(artifacts_dir, package, phase)
    _write_log(stdout_path, "")
    _write_log(stderr_path, detail + "\n")
    return PhaseResult(
        status="unavailable",
        exit_code=None,
        duration_seconds=0.0,
        stdout_path=_relative(stdout_path, artifacts_dir),
        stderr_path=_relative(stderr_path, artifacts_dir),
        classification="unavailable",
        detail=detail,
    )


def failed_phase(artifacts_dir: Path, package: str, phase: str, detail: str) -> PhaseResult:
    """Record a local validation failure that has no subprocess exit code."""
    stdout_path, stderr_path = _phase_paths(artifacts_dir, package, phase)
    _write_log(stdout_path, "")
    _write_log(stderr_path, detail + "\n")
    return PhaseResult(
        status="failed",
        exit_code=None,
        duration_seconds=0.0,
        stdout_path=_relative(stdout_path, artifacts_dir),
        stderr_path=_relative(stderr_path, artifacts_dir),
        classification=phase,
        detail=detail,
    )


def _venv_python(venv_dir: Path) -> Path:
    return venv_dir / ("Scripts/python.exe" if os.name == "nt" else "bin/python")


def _base_wheel(
    repository_root: Path, artifacts_dir: Path, python: str
) -> tuple[Path | None, PhaseResult | None]:
    base_path = repository_root / "bt_api" / "bt_api_base"
    if not (base_path / "pyproject.toml").is_file():
        return None, unavailable_phase(
            artifacts_dir,
            "bt_api_base",
            "base_build",
            f"base package is unavailable: {base_path}",
        )
    dist_dir = artifacts_dir / "base-dist"
    dist_dir.mkdir(parents=True, exist_ok=True)
    result = run_phase(
        command=[python, "-m", "pip", "wheel", "--no-deps", "--wheel-dir", str(dist_dir), "."],
        cwd=base_path,
        artifacts_dir=artifacts_dir,
        package="bt_api_base",
        phase="base_build",
        timeout_seconds=DEFAULT_TIMEOUT_SECONDS,
    )
    wheels = sorted(dist_dir.glob("*.whl"))
    return (wheels[-1] if result.status == "passed" and wheels else None), result


def _module_name(package_path: Path, package_name: str) -> str:
    metadata = package_path / "pyproject.toml"
    if metadata.is_file():
        try:
            data = load_toml(metadata)
            name = str((data.get("project") or {}).get("name") or package_name)
            return name.replace("-", "_")
        except (OSError, tomllib.TOMLDecodeError):
            pass
    return package_name.replace("-", "_")


def _offline_pytest_command(
    isolated_python: Path,
    package_path: Path,
    tests_dir: Path,
    *,
    collect_only: bool,
) -> list[str]:
    """Build an isolated pytest command that cannot execute live service tests."""
    command = [
        str(isolated_python),
        "-m",
        "pytest",
        "--confcutdir",
        str(package_path),
        "--disable-socket",
        "--allow-unix-socket",
        "tests",
    ]
    if (tests_dir / "network").is_dir():
        command.append("--ignore=tests/network")
    command.extend(["-m", OFFLINE_TEST_MARKER_EXPRESSION])
    if collect_only:
        command.append("--collect-only")
    command.append("-q")
    return command


def validate_package(
    *,
    package: str,
    profile: str,
    repository_root: Path,
    artifacts_dir: Path,
    python: str,
    base_wheel: Path | None,
) -> PackageResult:
    package_path = repository_root / "bt_api" / package
    result = PackageResult(
        package=package,
        profile=profile,
        package_path=str(package_path),
        status="failed",
        environment={"controller_python": python},
    )
    if not (package_path / "pyproject.toml").is_file():
        result.phases["resolve"] = unavailable_phase(
            artifacts_dir, package, "resolve", f"submodule/package unavailable: {package_path}"
        )
        result.status = "unavailable"
        result.classification = "unavailable"
        return result
    if base_wheel is None:
        result.phases["base_install"] = unavailable_phase(
            artifacts_dir, package, "base_install", "base wheel is unavailable"
        )
        result.status = "unavailable"
        result.classification = "base_build"
        return result

    venv_dir = artifacts_dir / "venvs" / package
    result.phases["venv"] = run_phase(
        command=[python, "-m", "venv", str(venv_dir)],
        cwd=repository_root,
        artifacts_dir=artifacts_dir,
        package=package,
        phase="venv",
        timeout_seconds=DEFAULT_TIMEOUT_SECONDS,
    )
    if result.phases["venv"].status != "passed":
        result.classification = "environment"
        return result
    isolated_python = _venv_python(venv_dir)
    result.environment["isolated_python"] = str(isolated_python)
    result.environment["base_wheel"] = str(base_wheel)

    result.phases["base_install"] = run_phase(
        command=[
            str(isolated_python),
            "-m",
            "pip",
            "install",
            str(base_wheel),
            "pytest>=7.0",
            "pytest-asyncio>=0.21.0",
            "pytest-socket>=0.7.0",
        ],
        cwd=repository_root,
        artifacts_dir=artifacts_dir,
        package=package,
        phase="base_install",
        timeout_seconds=DEFAULT_TIMEOUT_SECONDS,
    )
    if result.phases["base_install"].status != "passed":
        result.classification = "base_install"
        return result

    plugin_dist_dir = artifacts_dir / "plugin-dist" / package
    plugin_dist_dir.mkdir(parents=True, exist_ok=True)
    result.phases["build"] = run_phase(
        command=[
            str(isolated_python),
            "-m",
            "pip",
            "wheel",
            "--no-deps",
            "--wheel-dir",
            str(plugin_dist_dir),
            ".",
        ],
        cwd=package_path,
        artifacts_dir=artifacts_dir,
        package=package,
        phase="build",
        timeout_seconds=DEFAULT_TIMEOUT_SECONDS,
    )
    if result.phases["build"].status != "passed":
        result.classification = "build"
        return result
    plugin_wheels = sorted(plugin_dist_dir.glob("*.whl"))
    if not plugin_wheels:
        result.phases["build"] = failed_phase(
            artifacts_dir, package, "build", "wheel build completed without producing a wheel artifact"
        )
        result.classification = "build"
        return result
    plugin_wheel = plugin_wheels[-1]
    result.environment["plugin_wheel"] = str(plugin_wheel)

    result.phases["install"] = run_phase(
        command=[str(isolated_python), "-m", "pip", "install", str(plugin_wheel)],
        cwd=package_path,
        artifacts_dir=artifacts_dir,
        package=package,
        phase="install",
        timeout_seconds=DEFAULT_TIMEOUT_SECONDS,
    )
    if result.phases["install"].status != "passed":
        result.classification = "install"
        return result

    module_name = _module_name(package_path, package)
    result.phases["import"] = run_phase(
        command=[
            str(isolated_python),
            "-c",
            f"import importlib; importlib.import_module({module_name!r})",
        ],
        cwd=package_path,
        artifacts_dir=artifacts_dir,
        package=package,
        phase="import",
        timeout_seconds=DEFAULT_TIMEOUT_SECONDS,
        environment={"PYTHONPATH": ""},
    )
    if result.phases["import"].status != "passed":
        result.classification = "import"
        return result

    tests_dir = package_path / "tests"
    if not tests_dir.is_dir():
        result.phases["collection"] = PhaseResult(
            status="skipped",
            exit_code=None,
            duration_seconds=0.0,
            stdout_path="",
            stderr_path="",
            classification="no_tests",
            detail="package has no tests directory",
        )
        result.phases["test"] = result.phases["collection"]
        result.status = "passed"
        result.classification = "no_tests"
        return result

    test_environment = {
        "PYTHONPATH": "",
        "PYTHONDONTWRITEBYTECODE": "1",
        "SKIP_LIVE_TESTS": "true",
    }
    result.environment["test_selection"] = (
        f"offline markers: {OFFLINE_TEST_MARKER_EXPRESSION}; "
        "tests/network ignored when present"
    )

    result.phases["collection"] = run_phase(
        command=_offline_pytest_command(
            isolated_python, package_path, tests_dir, collect_only=True
        ),
        cwd=package_path,
        artifacts_dir=artifacts_dir,
        package=package,
        phase="collection",
        timeout_seconds=TEST_TIMEOUT_SECONDS,
        environment=test_environment,
    )
    if result.phases["collection"].status != "passed":
        result.classification = "collection"
        return result
    result.phases["test"] = run_phase(
        command=_offline_pytest_command(
            isolated_python, package_path, tests_dir, collect_only=False
        ),
        cwd=package_path,
        artifacts_dir=artifacts_dir,
        package=package,
        phase="test",
        timeout_seconds=TEST_TIMEOUT_SECONDS,
        environment=test_environment,
    )
    if result.phases["test"].status != "passed":
        result.classification = result.phases["test"].classification
        return result
    result.status = "passed"
    return result


def write_junit(results: Iterable[PackageResult], path: Path) -> None:
    suite = ET.Element("testsuite", name="submodule-validation")
    materialized = list(results)
    suite.set("tests", str(len(materialized)))
    suite.set("failures", str(sum(result.status == "failed" for result in materialized)))
    suite.set("skipped", str(sum(result.status == "unavailable" for result in materialized)))
    for result in materialized:
        case = ET.SubElement(
            suite,
            "testcase",
            classname=f"profile.{result.profile}",
            name=result.package,
        )
        details = json.dumps(asdict(result), ensure_ascii=False, sort_keys=True)
        if result.status == "unavailable":
            ET.SubElement(case, "skipped", message=result.classification).text = details
        elif result.status != "passed":
            ET.SubElement(case, "failure", message=result.classification).text = details
        ET.SubElement(case, "system-out").text = details
    path.parent.mkdir(parents=True, exist_ok=True)
    ET.ElementTree(suite).write(path, encoding="utf-8", xml_declaration=True)


def write_markdown(results: Iterable[PackageResult], path: Path) -> None:
    rows = list(results)
    lines = [
        "# Submodule validation index",
        "",
        "The JSON and JUnit files are the canonical machine-readable evidence.",
        "",
        "| Package | Profile | Result | Classification | Logs |",
        "| --- | --- | --- | --- | --- |",
    ]
    for result in rows:
        logs = []
        for phase_name, phase in result.phases.items():
            if phase.stderr_path:
                logs.append(f"[{phase_name} stderr]({phase.stderr_path})")
        lines.append(
            f"| {result.package} | {result.profile} | {result.status} | "
            f"{result.classification or '-'} | {'<br>'.join(logs) or '-'} |"
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def run_validation(
    *,
    profile: str,
    repository_root: Path,
    artifacts_dir: Path,
    config_path: Path,
    python: str = sys.executable,
) -> dict[str, Any]:
    """Run a profile and return/write a complete evidence payload."""
    started_at = utc_now()
    artifacts_dir.mkdir(parents=True, exist_ok=True)
    config = load_toml(config_path)
    bundle_catalog = load_toml(repository_root / "bt_api_py" / "configs" / "exchange-bundles.toml")
    package_names = package_names_for_profile(profile, config, bundle_catalog, repository_root)
    base_wheel, base_phase = _base_wheel(repository_root, artifacts_dir, python)
    results: list[PackageResult] = []
    for package in package_names:
        if package == "bt_api_base":
            base_result = PackageResult(
                package=package,
                profile=profile,
                package_path=str(repository_root / "bt_api" / package),
                status="passed" if base_wheel is not None else "unavailable",
                phases={"base_build": base_phase} if base_phase is not None else {},
                environment={"controller_python": python},
                classification="" if base_wheel is not None else "base_build",
            )
            results.append(base_result)
            continue
        results.append(
            validate_package(
                package=package,
                profile=profile,
                repository_root=repository_root,
                artifacts_dir=artifacts_dir,
                python=python,
                base_wheel=base_wheel,
            )
        )
    payload = {
        "schema_version": 1,
        "profile": profile,
        "repository_root": str(repository_root),
        "started_at": started_at,
        "finished_at": utc_now(),
        "python": python,
        "result": "passed"
        if results and all(item.status == "passed" for item in results)
        else "failed",
        "packages": [asdict(item) for item in results],
    }
    (artifacts_dir / "submodule-validation.json").write_text(
        json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8"
    )
    write_junit(results, artifacts_dir / "submodule-validation.junit.xml")
    write_markdown(results, artifacts_dir / "submodule-validation.md")
    return payload


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", default="core-reference")
    parser.add_argument("--artifacts-dir", type=Path, required=True)
    parser.add_argument("--config", type=Path, default=Path("configs/submodule-validation.toml"))
    parser.add_argument("--repository-root", type=Path, default=Path.cwd())
    parser.add_argument(
        "--diagnostic",
        action="store_true",
        help="Keep a non-zero evidence result in JSON but exit zero for scheduled diagnostics.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    payload = run_validation(
        profile=args.profile,
        repository_root=args.repository_root.resolve(),
        artifacts_dir=args.artifacts_dir.resolve(),
        config_path=args.config.resolve(),
    )
    print(json.dumps({"profile": payload["profile"], "result": payload["result"]}))
    return 0 if payload["result"] == "passed" or args.diagnostic else 1


if __name__ == "__main__":
    raise SystemExit(main())
