"""
Bitfinex REST API request base class.
Handles authentication (HMAC SHA384), signing, and all REST API methods.
"""

import hashlib
import hmac
import json
import time
from typing import Any
from urllib.parse import urlencode

from bt_api_py.containers.balances.bitfinex_balance import BitfinexSpotRequestBalanceData
from bt_api_py.containers.bars.bitfinex_bar import BitfinexRequestBarData
from bt_api_py.containers.exchanges.bitfinex_exchange_data import BitfinexExchangeDataSpot
from bt_api_py.containers.orderbooks.bitfinex_orderbook import BitfinexRequestOrderBookData
from bt_api_py.containers.orders.bitfinex_order import BitfinexRequestOrderData
from bt_api_py.containers.requestdatas.request_data import RequestData
from bt_api_py.containers.tickers.bitfinex_ticker import BitfinexRequestTickerData
from bt_api_py.containers.trades.bitfinex_trade import BitfinexRequestTradeData
from bt_api_py.exceptions import QueueNotInitializedError
from bt_api_py.feeds.capability import Capability
from bt_api_py.feeds.feed import Feed
from bt_api_py.feeds.http_client import HttpClient
from bt_api_py.functions.utils import update_extra_data
from bt_api_py.logging_factory import get_logger


class BitfinexRequestData(Feed):
    """Bitfinex REST API base class.

    Uses Feed.http_request() for HTTP calls, supports "METHOD /path" format.
    Authentication uses HMAC SHA384 with bfx-apikey / bfx-signature headers.
    """

    @classmethod
    def _capabilities(cls) -> set[Capability]:
        return {
            Capability.GET_TICK,
            Capability.GET_DEPTH,
            Capability.GET_KLINE,
            Capability.MAKE_ORDER,
            Capability.CANCEL_ORDER,
            Capability.QUERY_ORDER,
            Capability.QUERY_OPEN_ORDERS,
            Capability.GET_DEALS,
            Capability.GET_BALANCE,
            Capability.GET_ACCOUNT,
            Capability.GET_EXCHANGE_INFO,
            Capability.GET_SERVER_TIME,
        }

    def __init__(self, data_queue: Any = None, **kwargs: Any) -> None:
        super().__init__(data_queue, **kwargs)
        self.data_queue = data_queue
        self.api_key = kwargs.get("api_key") or kwargs.get("public_key")
        self.api_secret = kwargs.get("api_secret") or kwargs.get("private_key")
        self.asset_type = kwargs.get("asset_type", "SPOT")
        self.exchange_name = kwargs.get("exchange_name", "BITFINEX___SPOT")
        self.logger_name = kwargs.get("logger_name", "bitfinex_spot_feed.log")
        self._params = kwargs.get("exchange_data", BitfinexExchangeDataSpot())

        self.request_logger = get_logger("bitfinex_spot_feed")
        self.async_logger = get_logger("bitfinex_spot_feed")
        self._http_client = HttpClient(venue=self.exchange_name, timeout=30)

    # ── authentication ──────────────────────────────────────────

    def sign(self, path, nonce, body=""):
        """Generate HMAC SHA384 signature for Bitfinex API

        Args:
            path: API endpoint path (e.g., '/v2/auth/r/wallets')
            nonce: Request nonce (timestamp in microseconds)
            body: Request body JSON string

        Returns:
            Hexadecimal signature string
        """
        signature_payload = f"/api{path}{nonce}{body}"
        signature = hmac.new(
            self.api_secret.encode(), signature_payload.encode(), hashlib.sha384
        ).hexdigest()
        return signature

    # ── core request helpers ────────────────────────────────────

    def push_data_to_queue(self, data):
        if self.data_queue is not None:
            self.data_queue.put(data)
        else:
            raise QueueNotInitializedError("data_queue not initialized")

    def request(self, path, params=None, body=None, extra_data=None, timeout=10, is_sign=False):
        """HTTP request function using Feed.http_request().

        Args:
            path: Request path in "METHOD /endpoint" format
            params: URL query parameters
            body: Request body for POST requests
            extra_data: Extra data generated by user
            timeout: Request timeout in seconds
            is_sign: Whether to sign the request

        Returns:
            RequestData object
        """
        if params is None:
            params: dict[str, Any] = {}
        if extra_data is None:
            extra_data = {}
        method, endpoint = path.split(" ", 1)

        # Build URL with query string
        query_string = urlencode(params) if params else ""
        url = f"{self._params.rest_url}{endpoint}"
        if query_string:
            url = f"{url}?{query_string}"

        # Build headers
        headers = {"Content-Type": "application/json"}
        if is_sign and self.api_key and self.api_secret:
            nonce = str(int(time.time() * 1000000))
            body_str = json.dumps(body) if body else ""
            sig = self.sign(endpoint, nonce, body_str)
            headers.update(
                {
                    "bfx-apikey": self.api_key,
                    "bfx-nonce": nonce,
                    "bfx-signature": sig,
                }
            )

        # Make HTTP request via Feed.http_request()
        response = self.http_request(method, url, headers, body, timeout)

        return RequestData(response, extra_data)

    async def async_request(
        self, path, params=None, body=None, extra_data=None, timeout=10, is_sign=False
    ):
        """Async HTTP request function.

        Args:
            path: Request path in "METHOD /endpoint" format
            params: URL query parameters
            body: Request body for POST requests
            extra_data: Extra data generated by user
            timeout: Request timeout in seconds
            is_sign: Whether to sign the request

        Returns:
            RequestData object
        """
        if params is None:
            params: dict[str, Any] = {}
        if extra_data is None:
            extra_data = {}
        method, endpoint = path.split(" ", 1)

        # Build URL with query string
        query_string = urlencode(params) if params else ""
        url = f"{self._params.rest_url}{endpoint}"
        if query_string:
            url = f"{url}?{query_string}"

        # Build headers
        headers = {"Content-Type": "application/json"}
        if is_sign and self.api_key and self.api_secret:
            nonce = str(int(time.time() * 1000000))
            body_str = json.dumps(body) if body else ""
            sig = self.sign(endpoint, nonce, body_str)
            headers.update(
                {
                    "bfx-apikey": self.api_key,
                    "bfx-nonce": nonce,
                    "bfx-signature": sig,
                }
            )

        # Make async HTTP request
        response = await self._http_client.async_request(
            method=method,
            url=url,
            headers=headers,
            json_data=body if method in ["POST", "PUT", "DELETE"] else None,
        )

        self.async_logger.info(f"Async Request: {method} {url}")
        return RequestData(response, extra_data)

    def async_callback(self, future):
        """Callback function for async requests."""
        try:
            result = future.result()
            self.push_data_to_queue(result)
        except Exception as e:
            self.async_logger.warning(f"async_callback::{e}")

    # ==================== Market Data APIs ====================

    def _get_server_time(self, extra_data=None, **kwargs):
        """Get server time"""
        request_type = "get_server_time"
        path = self._params.get_rest_path(request_type)
        params: dict[str, Any] = {}

        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": self._get_server_time_normalize_function,
            },
        )

        return path, params, extra_data

    @staticmethod
    def _get_server_time_normalize_function(input_data, extra_data):
        """Normalize server time response"""
        status = input_data is not None
        server_time = None
        if status and isinstance(input_data, list) and len(input_data) > 0:
            server_time = input_data[0]
        return [{"server_time": server_time}], status

    def _get_exchange_info(self, symbol=None, extra_data=None, **kwargs):
        """Get exchange information"""
        request_type = "get_exchange_info"
        path = self._params.get_rest_path(request_type)
        params: dict[str, Any] = {}

        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": self._get_exchange_info_normalize_function,
            },
        )

        return path, params, extra_data

    @staticmethod
    def _get_exchange_info_normalize_function(input_data, extra_data):
        """Normalize exchange info response"""
        status = input_data is not None
        symbols = input_data if isinstance(input_data, list) else []
        return [{"symbols": symbols}], status

    def _get_ticker(self, symbol, extra_data=None, **kwargs):
        """Get ticker information"""
        request_symbol = self._params.get_symbol(symbol)
        request_type = "get_tick"
        path = self._params.get_rest_path(request_type)
        # Replace {symbol} placeholder
        path = path.replace("{symbol}", request_symbol)

        params: dict[str, Any] = {}

        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": self._get_ticker_normalize_function,
            },
        )

        return path, params, extra_data

    @staticmethod
    def _get_ticker_normalize_function(input_data, extra_data):
        """Normalize ticker response data"""
        status = input_data is not None
        symbol_name = extra_data["symbol_name"]
        asset_type = extra_data["asset_type"]

        if isinstance(input_data, list) and len(input_data) >= 8:
            data = [BitfinexRequestTickerData(input_data, symbol_name, asset_type, True)]
        else:
            data = []

        return data, status

    def _get_order_book(self, symbol, precision="P0", length="25", extra_data=None, **kwargs):
        """Get order book data"""
        request_symbol = self._params.get_symbol(symbol)
        request_type = "get_depth"
        path = self._params.get_rest_path(request_type)
        path = path.replace("{symbol}", request_symbol)
        path = path.replace("{precision}", precision)
        path = path.replace("{len}", length)

        params: dict[str, Any] = {}

        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": self._get_order_book_normalize_function,
            },
        )

        return path, params, extra_data

    @staticmethod
    def _get_order_book_normalize_function(input_data, extra_data):
        """Normalize order book response data"""
        status = input_data is not None
        symbol_name = extra_data["symbol_name"]
        asset_type = extra_data["asset_type"]

        if isinstance(input_data, list):
            data = [BitfinexRequestOrderBookData(input_data, symbol_name, asset_type, True)]
        else:
            data = []

        return data, status

    def _get_klines(self, symbol, period="1m", limit=100, extra_data=None, **kwargs):
        """Get kline/candlestick data"""
        request_symbol = self._params.get_symbol(symbol)
        request_period = self._params.get_period(period)
        request_type = "get_kline"
        path = self._params.get_rest_path(request_type)
        path = path.replace("{symbol}", request_symbol)
        path = path.replace("{period}", request_period)
        path = path.replace("{limit}", str(limit))
        # Remove unused placeholders
        path = path.replace("&start={start}", "").replace("&end={end}", "")

        params: dict[str, Any] = {}

        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": self._get_klines_normalize_function,
            },
        )

        return path, params, extra_data

    @staticmethod
    def _get_klines_normalize_function(input_data, extra_data):
        """Normalize kline response data"""
        status = input_data is not None
        symbol_name = extra_data["symbol_name"]
        asset_type = extra_data["asset_type"]

        if isinstance(input_data, list):
            data = [BitfinexRequestBarData(input_data, symbol_name, asset_type, True)]
        else:
            data = []

        return data, status

    def _get_trade_history(self, symbol, limit=100, extra_data=None, **kwargs):
        """Get recent trades"""
        request_symbol = self._params.get_symbol(symbol)
        request_type = "get_historical_trades"
        path = self._params.get_rest_path(request_type)
        path = path.replace("{symbol}", request_symbol)
        path = path.replace("{limit}", str(limit))

        params: dict[str, Any] = {}

        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": self._get_trade_history_normalize_function,
            },
        )

        return path, params, extra_data

    @staticmethod
    def _get_trade_history_normalize_function(input_data, extra_data):
        """Normalize trade history response data"""
        status = input_data is not None
        symbol_name = extra_data["symbol_name"]
        asset_type = extra_data["asset_type"]

        if isinstance(input_data, list):
            data = [BitfinexRequestTradeData(input_data, symbol_name, asset_type, True)]
        else:
            data = []

        return data, status

    # ==================== Private APIs ====================

    def _make_order(
        self,
        symbol,
        vol,
        price=None,
        order_type="buy-limit",
        offset="open",
        post_only=False,
        client_order_id=None,
        extra_data=None,
        **kwargs,
    ):
        """Create an order"""
        request_symbol = self._params.get_symbol(symbol)
        request_type = "make_order"
        path = self._params.get_rest_path(request_type)

        # Parse order type
        side, order_type_subtype = order_type.split("-")

        # Prepare body parameters
        params = {
            "type": order_type_subtype.upper(),
            "symbol": request_symbol,
            "amount": str(vol),
            "flags": 64 if post_only else 0,
        }

        if price is not None and order_type_subtype != "market":
            params["price"] = str(price)

        if client_order_id is not None:
            params["cid"] = int(client_order_id)

        if "lev" in kwargs:
            params["lev"] = kwargs["lev"]

        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "post_only": post_only,
                "normalize_function": self._make_order_normalize_function,
            },
        )

        return path, params, extra_data

    @staticmethod
    def _make_order_normalize_function(input_data, extra_data):
        """Normalize order response data"""
        status = input_data is not None
        symbol_name = extra_data["symbol_name"]
        asset_type = extra_data["asset_type"]

        if isinstance(input_data, list):
            data = [BitfinexRequestOrderData(i, symbol_name, asset_type, True) for i in input_data]
        elif isinstance(input_data, dict):
            data = [BitfinexRequestOrderData(input_data, symbol_name, asset_type, True)]
        else:
            data = []

        return data, status

    def _cancel_order(
        self, symbol=None, order_id=None, client_order_id=None, extra_data=None, **kwargs
    ):
        """Cancel an order"""
        request_type = "cancel_order"
        path = self._params.get_rest_path(request_type)

        params: dict[str, Any] = {}
        if order_id is not None:
            params["id"] = order_id
        if client_order_id is not None:
            params["cid"] = client_order_id

        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "order_id": order_id,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": self._cancel_order_normalize_function,
            },
        )

        return path, params, extra_data

    @staticmethod
    def _cancel_order_normalize_function(input_data, extra_data):
        """Normalize cancel order response data"""
        status = input_data is not None
        asset_type = extra_data["asset_type"]

        if isinstance(input_data, list) and len(input_data) > 0:
            order_id = extra_data.get("order_id")
            cancel_data = {"id": input_data[0], "status": "SUCCESS"}
            data = [BitfinexRequestOrderData(cancel_data, f"order_{order_id}", asset_type, True)]
        else:
            data = []

        return data, status

    def _get_order(
        self, symbol=None, order_id=None, client_order_id=None, extra_data=None, **kwargs
    ):
        """Query an order"""
        request_type = "get_order"
        path = self._params.get_rest_path(request_type)
        if order_id is not None:
            path = path.replace("{id}", str(order_id))

        params: dict[str, Any] = {}

        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "order_id": order_id,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": self._get_order_normalize_function,
            },
        )

        return path, params, extra_data

    @staticmethod
    def _get_order_normalize_function(input_data, extra_data):
        """Normalize query order response data"""
        status = input_data is not None
        symbol_name = extra_data.get("symbol_name")
        asset_type = extra_data["asset_type"]

        if isinstance(input_data, (list, dict)):
            data = [BitfinexRequestOrderData(input_data, symbol_name, asset_type, True)]
        else:
            data = []

        return data, status

    def _get_open_orders(self, symbol=None, extra_data=None, **kwargs):
        """Get open orders"""
        request_type = "get_open_orders"
        path = self._params.get_rest_path(request_type)

        params: dict[str, Any] = {}
        if symbol:
            request_symbol = self._params.get_symbol(symbol)
            path = path.replace("{symbol}", request_symbol)

        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": self._get_open_orders_normalize_function,
            },
        )

        return path, params, extra_data

    @staticmethod
    def _get_open_orders_normalize_function(input_data, extra_data):
        """Normalize open orders response data"""
        status = input_data is not None
        symbol_name = extra_data.get("symbol_name")
        asset_type = extra_data["asset_type"]

        if isinstance(input_data, list):
            data = [BitfinexRequestOrderData(input_data, symbol_name, asset_type, True)]
        else:
            data = []

        return data, status

    def _get_account(self, extra_data=None, **kwargs):
        """Get account information"""
        request_type = "get_account"
        path = self._params.get_rest_path(request_type)
        params: dict[str, Any] = {}

        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": self._get_account_normalize_function,
            },
        )

        return path, params, extra_data

    @staticmethod
    def _get_account_normalize_function(input_data, extra_data):
        """Normalize account response data"""
        status = input_data is not None
        asset_type = extra_data["asset_type"]

        if isinstance(input_data, list):
            data = [BitfinexSpotRequestBalanceData(input_data, asset_type, True)]
        else:
            data = []

        return data, status
