"""
Coinbase REST API request base class.
Handles authentication (HMAC SHA256 / JWT), signing, and all REST API methods.
"""

import base64
import hashlib
import hmac
import json
import time
from urllib import parse

from bt_api_py.containers.exchanges.coinbase_exchange_data import CoinbaseExchangeDataSpot
from bt_api_py.containers.requestdatas.request_data import RequestData
from bt_api_py.feeds.feed import Feed
from bt_api_py.functions.log_message import SpdLogManager


class CoinbaseRequestData(Feed):
    """Base class for Coinbase REST API requests.

    Uses Feed.http_request() for HTTP calls, supports "METHOD /path" format.
    Authentication uses HMAC SHA256 with CB-ACCESS-KEY / CB-ACCESS-SIGN headers
    (Coinbase Advanced Trade API v3 style).
    """

    def __init__(self, data_queue, **kwargs):
        super().__init__(data_queue, **kwargs)
        self.data_queue = data_queue
        self.api_key = kwargs.get("api_key") or kwargs.get("public_key")
        self.private_key = kwargs.get("private_key")
        self.passphrase = kwargs.get("passphrase", "")
        self.asset_type = kwargs.get("asset_type", "SPOT")
        self.exchange_name = kwargs.get("exchange_name", "COINBASE___SPOT")
        self.logger_name = kwargs.get("logger_name", "coinbase_feed.log")
        self._params = CoinbaseExchangeDataSpot()

        self.request_logger = SpdLogManager(
            "./logs/" + self.logger_name, "request", 0, 0, False
        ).create_logger()
        self.async_logger = SpdLogManager(
            "./logs/" + self.logger_name, "async_request", 0, 0, False
        ).create_logger()

    # ── authentication ──────────────────────────────────────────

    # noinspection PyMethodMayBeStatic
    def signature(self, timestamp, method, request_path, secret_key, body=""):
        """Generate Coinbase API signature (HMAC SHA256).

        Args:
            timestamp: Request timestamp string
            method: HTTP method (GET, POST, DELETE)
            request_path: Request endpoint path with query string
            secret_key: API secret key
            body: Request body string (empty for GET/DELETE)

        Returns:
            Base64 encoded HMAC SHA256 signature
        """
        message = str(timestamp) + method.upper() + request_path + body
        mac = hmac.new(
            bytes(secret_key, encoding="utf-8"),
            bytes(message, encoding="utf-8"),
            digestmod=hashlib.sha256,
        )
        return base64.b64encode(mac.digest()).decode()

    # noinspection PyMethodMayBeStatic
    def get_header(self, api_key, sign, timestamp):
        """Generate request headers with authentication.

        Args:
            api_key: API key
            sign: Base64 encoded signature
            timestamp: Request timestamp string

        Returns:
            Dictionary of request headers
        """
        return {
            "CB-ACCESS-KEY": api_key,
            "CB-ACCESS-SIGN": sign,
            "CB-ACCESS-TIMESTAMP": str(timestamp),
            "Content-Type": "application/json",
        }

    # ── core request helpers ────────────────────────────────────

    def push_data_to_queue(self, data):
        if self.data_queue is not None:
            self.data_queue.put(data)
        else:
            assert 0, "Queue not initialized"

    def request(self, path, params=None, body=None, extra_data=None, timeout=10, is_sign=False):
        """HTTP request function using Feed.http_request().

        Args:
            path: Request path in "METHOD /endpoint" format
            params: URL query parameters
            body: Request body for POST requests
            extra_data: Extra data generated by user
            timeout: Request timeout in seconds
            is_sign: Whether to sign the request

        Returns:
            RequestData object
        """
        if params is None:
            params = {}
        method, endpoint = path.split(" ", 1)

        # Build URL with query string
        query_string = parse.urlencode(params) if params else ""
        url = f"{self._params.rest_url}{endpoint}"
        if query_string:
            url = f"{url}?{query_string}"
            request_path = f"{endpoint}?{query_string}"
        else:
            request_path = endpoint

        headers = {}
        if is_sign and self.api_key and self.private_key:
            timestamp = str(int(time.time()))
            body_str = json.dumps(body) if body else ""
            sign = self.signature(timestamp, method, request_path, self.private_key, body_str)
            headers = self.get_header(self.api_key, sign, timestamp)

        res = self.http_request(method, url, headers, body, timeout)
        return RequestData(res, extra_data)

    async def async_request(
        self, path, params=None, body=None, extra_data=None, timeout=5, is_sign=False
    ) -> RequestData:
        """Async HTTP request function.

        Args:
            path: Request path in "METHOD /endpoint" format
            params: URL query parameters
            body: Request body
            extra_data: Extra data
            timeout: Request timeout in seconds
            is_sign: Whether to sign the request

        Returns:
            RequestData object
        """
        if params is None:
            params = {}
        method, endpoint = path.split(" ", 1)

        query_string = parse.urlencode(params) if params else ""
        url = f"{self._params.rest_url}{endpoint}"
        if query_string:
            url = f"{url}?{query_string}"
            request_path = f"{endpoint}?{query_string}"
        else:
            request_path = endpoint

        headers = {}
        if is_sign and self.api_key and self.private_key:
            timestamp = str(int(time.time()))
            body_str = json.dumps(body) if body else ""
            sign = self.signature(timestamp, method, request_path, self.private_key, body_str)
            headers = self.get_header(self.api_key, sign, timestamp)

        res = await self.async_http_request(method, url, headers, body, timeout)
        return RequestData(res, extra_data)

    def async_callback(self, future):
        """Callback function for async requests.

        Args:
            future: asyncio future object
        """
        try:
            result = future.result()
            self.push_data_to_queue(result)
        except Exception as e:
            self.async_logger.warn(f"async_callback::{e}")
