"""
标记价格类，用于确定标记价格的属性和方法
标记价格，更新频率比较低，mark_price参数直接使用json格式
"""

from typing import Any, Self

from bt_api_py.containers.auto_init_mixin import AutoInitMixin


class MarkPriceData(AutoInitMixin):
    """保存标记价格信息."""

    def __init__(self, mark_price_info: Any, has_been_json_encoded: Any = False) -> None:
        self.event = "MarkPriceEvent"
        self.mark_price_info = mark_price_info
        self.has_been_json_encoded = has_been_json_encoded

    def init_data(self) -> Self:
        """
        init data from request or wss
        :return: Self for method chaining
        """
        raise NotImplementedError

    def get_all_data(self) -> dict[str, Any]:
        raise NotImplementedError

    def get_event(self) -> str:
        """
        get event type
        :return: str, MarkPriceEvent
        """
        return self.event

    def get_exchange_name(self) -> str:
        """
        get exchange name
        :return: str, eg BINANCE & OKX
        """
        raise NotImplementedError

    def get_server_time(self) -> float:
        """
        get server time generated by the server
        :return: float, timestamp
        """
        raise NotImplementedError

    def get_local_update_time(self) -> float:
        """
        get local update time for the data generate
        :return: float, timestamp
        """
        raise NotImplementedError

    def get_symbol_name(self) -> str:
        """
        get the data's symbol
        :return: str, symbol's name
        """
        raise NotImplementedError

    def get_mark_price(self) -> float | None:
        """
        get mark_price
        :return: float, mark_price or None
        """
        raise NotImplementedError

    def __str__(self) -> str:
        raise NotImplementedError

    def __repr__(self) -> str:
        raise NotImplementedError
