#!/usr/bin/env python3
"""
split_ctp_wrapper.py — 自动拆分 SWIG 生成的 ctp.py 为多个分类子模块 (v2.1)

用法:
    python scripts/split_ctp_wrapper.py
    python scripts/split_ctp_wrapper.py --dry-run

原理 (v2.1 — 真正代码拆分 + 保留关键导入):
    解析 bt_api_py/ctp/ctp.py，将实际代码提取到各子模块中:

    1. _ctp_base.py          — SWIG 基础设施 (preamble 共享代码)
                                **现在会保留关键导入: _ctp, stderr, print_exception, weakref**
    2. ctp_constants.py      — THOST_* 常量赋值语句
    3. ctp_md_api.py         — CThostFtdcMdSpi / CThostFtdcMdApi 类定义
    4. ctp_trader_api.py     — CThostFtdcTraderSpi / CThostFtdcTraderApi 类定义
    5. ctp_structs_*.py      — 各类 CThostFtdc*Field 结构体类定义
    6. ctp.py                — 替换为向后兼容垫片 (从子模块重新导入全部符号)

v2.1 更新 (2026-02-28):
    修复了 _ctp_base.py 生成时丢失关键导入的问题。现在会自动检测并恢复:
    - from sys import stderr, float_info
    - from traceback import print_exc, print_exception
    - import weakref
    - from . import _ctp (或 import _ctp)

    这些导入是子模块正常工作所必需的。
"""

import os
import re
import sys
from collections import OrderedDict

# ---------------------------------------------------------------------------
#  路径配置
# ---------------------------------------------------------------------------
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.dirname(_SCRIPT_DIR)
_CTP_PKG_DIR = os.path.join(_PROJECT_ROOT, "bt_api_py", "ctp")
_CTP_PY_PATH = os.path.join(_CTP_PKG_DIR, "ctp.py")

# ---------------------------------------------------------------------------
#  自动生成文件的标记 (用于清理旧文件)
# ---------------------------------------------------------------------------
_AUTO_GEN_HEADER = "# AUTO-GENERATED by split_ctp_wrapper.py — DO NOT EDIT\n"

# ---------------------------------------------------------------------------
#  子模块描述
# ---------------------------------------------------------------------------
_MODULE_DESCRIPTIONS = {
    "ctp_constants": "CTP 常量定义 (THOST_* 枚举值)",
    "ctp_md_api": "CTP 行情 API (CThostFtdcMdSpi / CThostFtdcMdApi)",
    "ctp_trader_api": "CTP 交易 API (CThostFtdcTraderSpi / CThostFtdcTraderApi)",
    "ctp_structs_common": "CTP 通用结构 (登录/认证/用户/经纪商/结算等)",
    "ctp_structs_order": "CTP 订单相关结构 (报单/撤单/执行/询价/组合等)",
    "ctp_structs_trade": "CTP 成交相关结构",
    "ctp_structs_position": "CTP 持仓相关结构",
    "ctp_structs_account": "CTP 账户/资金相关结构",
    "ctp_structs_market": "CTP 行情/合约/产品/交易所相关结构",
    "ctp_structs_query": "CTP 查询请求参数结构 (Qry*)",
    "ctp_structs_transfer": "CTP 银期转账/签约/验证相关结构",
    "ctp_structs_risk": "CTP 风控/保证金/手续费/风险模型相关结构",
}

# 需要清理的文件名 (包括 _ctp_base 和 ctp.py 兼容垫片)
_ALL_GENERATED_FILES = list(_MODULE_DESCRIPTIONS.keys()) + ["_ctp_base"]


# ===================================================================
#  分类逻辑
# ===================================================================


def classify_class(name: str) -> str:
    """将一个 CThostFtdc* 类名分类到对应的子模块。

    分类优先级: 精确匹配 > 前缀匹配 > 关键词包含 > 兜底(common)
    """
    # ---- 1. API 类 (精确匹配) ----
    if name in ("CThostFtdcMdSpi", "CThostFtdcMdApi"):
        return "ctp_md_api"
    if name in ("CThostFtdcTraderSpi", "CThostFtdcTraderApi"):
        return "ctp_trader_api"

    # 去掉公共前缀 CThostFtdc，用剩余部分做关键词匹配
    s = name[len("CThostFtdc") :] if name.startswith("CThostFtdc") else name

    # ---- 2. 查询参数结构 (Qry* / Query*) ----
    if s.startswith("Qry") or s.startswith("Query"):
        return "ctp_structs_query"

    # ---- 3. 风险模型 (前缀匹配) ----
    _risk_prefixes = (
        "SyncDelta",
        "SPBM",
        "SPMM",
        "RCAMS",
        "RULE",
        "RiskSettle",
        "Syncing",
        "SyncSPBM",
    )
    if any(s.startswith(p) for p in _risk_prefixes):
        return "ctp_structs_risk"

    # ---- 4. 银期转账/签约/验证 (前缀匹配) ----
    _transfer_prefixes = (
        "Transfer",
        "ReqOpenAccount",
        "ReqCancelAccount",
        "ReqChangeAccount",
        "ReserveOpenAccount",
        "ReqFutureSign",
        "RspFutureSign",
        "ReqSyncKey",
        "RspSyncKey",
        "ReqRepeal",
        "RspRepeal",
        "Notify",
        "ReqDayEnd",
        "VerifyCust",
        "VerifyFuture",
        "VerifyInvestor",
        "Accountregister",
        "SecAgent",
        "ReqQueryAccount",
        "RspQueryAccount",
        "ReqQueryTradeResult",
        "RspQueryTradeResult",
        "ReturnResult",
        "ReqApiHandshake",
        "RspApiHandshake",
        "ReqVerifyApiKey",
        "CFMMCTradingAccountToken",
        "CFMMCTradingAccountKey",
    )
    if any(s.startswith(p) for p in _transfer_prefixes):
        return "ctp_structs_transfer"
    # 银行转账关键词
    _bank_keywords = (
        "BankToFuture",
        "FutureToBank",
        "OpenAccountConfirm",
    )
    if any(kw in s for kw in _bank_keywords):
        return "ctp_structs_transfer"

    # ---- 5. 订单相关 (关键词包含，排除保证金/手续费) ----
    _order_keywords = (
        "Order",
        "Quote",
        "ForQuote",
        "OptionSelfClose",
        "CombAction",
        "BatchOrder",
    )
    _risk_keywords_excl = ("Margin", "Commission", "TradingRight", "OrderComm")
    if any(kw in s for kw in _order_keywords):
        if not any(kw in s for kw in _risk_keywords_excl):
            return "ctp_structs_order"

    # ---- 6. 成交相关 (精确后缀匹配) ----
    if s in ("TradeField", "TradeParamField"):
        return "ctp_structs_trade"

    # ---- 7. 持仓相关 ----
    if "Position" in s:
        return "ctp_structs_position"

    # ---- 8. 账户/资金相关 ----
    _account_keywords = (
        "TradingAccount",
        "SyncDeposit",
        "SyncFundMortgage",
        "SyncDelaySwap",
    )
    if any(kw in s for kw in _account_keywords):
        return "ctp_structs_account"

    # ---- 9. 行情/合约/产品/交易所 (排除订单/保证金等) ----
    _market_keywords = (
        "MarketData",
        "DepthMarket",
        "Instrument",
        "Product",
        "Exchange",
        "Dissemination",
        "FrontInfo",
    )
    _market_excl = (
        "Margin",
        "Commission",
        "TradingRight",
        "OrderComm",
        "ExchangeOrder",
        "ExchangeExec",
        "ExchangeQuote",
        "ExchangeForQuote",
        "ExchangeBatch",
        "ExchangeOption",
        "ExchangeComb",
    )
    if any(kw in s for kw in _market_keywords):
        if not any(kw in s for kw in _market_excl):
            return "ctp_structs_market"

    # ---- 10. 风控/保证金/手续费 ----
    _risk_keywords = (
        "Margin",
        "Commission",
        "StrikeOffset",
        "EWarrant",
        "WithDraw",
        "OptionInstr",
        "MMInstrument",
        "MMOption",
        "TradingRight",
    )
    if any(kw in s for kw in _risk_keywords):
        return "ctp_structs_risk"

    # ---- 11. 兜底: 通用 ----
    return "ctp_structs_common"


# ===================================================================
#  解析 ctp.py — 提取 preamble / 常量 / 类代码块
# ===================================================================


def parse_ctp_py(ctp_py_path: str):
    """解析 ctp.py，提取 preamble、常量代码和各个类的代码块。

    Returns:
        preamble_code:  str   — SWIG 基础设施源码
        constants_code: str   — 常量赋值语句源码
        class_blocks:   OrderedDict[str, str] — {class_name: source_code}
        constant_names: list[str] — 常量名列表
        class_names:    list[str] — 类名列表 (保持原始顺序)
    """
    with open(ctp_py_path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    # ---- 找到三个区域的边界 ----
    first_const = None
    first_class = None

    for i, line in enumerate(lines):
        if first_const is None and re.match(r"^THOST_\w+\s*=\s*_ctp\.", line):
            first_const = i
        if first_class is None and re.match(r"^class\s+CThostFtdc", line):
            first_class = i
            break

    if first_const is None or first_class is None:
        raise ValueError("Cannot locate constant/class boundaries in ctp.py")

    preamble_code = "".join(lines[:first_const])
    constants_code = "".join(lines[first_const:first_class])

    # ---- 提取常量名 ----
    constant_names = re.findall(r"^(THOST_\w+)\s*=\s*_ctp\.", constants_code, re.MULTILINE)

    # ---- 提取各类代码块 ----
    class_region = lines[first_class:]

    # 找所有 class 起始位置
    class_starts = []
    for i, line in enumerate(class_region):
        m = re.match(r"^class\s+(CThostFtdc\w+)\s*\(", line)
        if m:
            class_starts.append((i, m.group(1)))

    class_blocks = OrderedDict()
    class_names = []
    for idx, (start, name) in enumerate(class_starts):
        end = class_starts[idx + 1][0] if idx + 1 < len(class_starts) else len(class_region)
        class_blocks[name] = "".join(class_region[start:end])
        class_names.append(name)

    return preamble_code, constants_code, class_blocks, constant_names, class_names


# ===================================================================
#  确定子模块所需的 _ctp_base 导入
# ===================================================================


def _determine_imports(code: str, is_constants: bool = False) -> str:
    """根据代码内容确定需要从 _ctp_base 导入的符号。"""
    if is_constants:
        return "from ._ctp_base import _ctp"

    parts = ["_ctp"]
    if "_swig_repr" in code:
        parts.append("_swig_repr")
    if "weakref" in code:
        parts.append("weakref")
    if "stderr" in code:
        parts.append("stderr")
    if "print_exception" in code:
        parts.append("print_exception")
    if "print_exc" in code and "print_exception" not in code:
        parts.append("print_exc")

    return "from ._ctp_base import " + ", ".join(parts)


# ===================================================================
#  文件生成
# ===================================================================


def _write_file(filepath: str, content: str, dry_run: bool = False):
    """写入文件 (或在 dry_run 模式下跳过)。"""
    if dry_run:
        return
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)


def generate_base_module(preamble_code: str, output_dir: str, dry_run: bool = False):
    """生成 _ctp_base.py — 包含 SWIG 基础设施共享代码。

    CRITICAL: Preserves essential imports that were stripped during parsing:
    - from sys import stderr, float_info
    - from traceback import print_exc, print_exception
    - import weakref
    - from . import _ctp (or import _ctp)

    These imports are required by submodules that import from _ctp_base.
    """
    # Ensure critical imports are preserved in preamble
    # The preamble parsing may have stripped these, so we restore them
    import_lines = []

    # Check if imports are already in preamble
    has_stderr = "from sys import" in preamble_code and "stderr" in preamble_code
    has_traceback = "from traceback import" in preamble_code
    has_weakref = "import weakref" in preamble_code
    has_ctp_import = "import _ctp" in preamble_code or "from . import _ctp" in preamble_code

    # Add missing imports at the beginning
    if not has_stderr:
        import_lines.append("from sys import stderr, float_info")
    if not has_traceback:
        import_lines.append("from traceback import print_exc, print_exception")
    if not has_weakref:
        import_lines.append("\nimport weakref")

    # Ensure _ctp import is present (this is the most critical one)
    if not has_ctp_import:
        import_lines.extend(
            [
                "\nfrom sys import version_info as _swig_python_version_info",
                "# Import the low-level C/C++ module",
                'if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:',
                "    from . import _ctp",
                "else:",
                "    import _ctp",
            ]
        )

    # Construct the final content
    if import_lines:
        restored_imports = "\n".join(import_lines) + "\n\n"
    else:
        restored_imports = ""

    content = (
        _AUTO_GEN_HEADER
        + '"""SWIG 基础设施 — 被所有 CTP 子模块共享"""\n\n'
        + restored_imports
        + preamble_code
    )

    filepath = os.path.join(output_dir, "_ctp_base.py")
    _write_file(filepath, content, dry_run)
    label = "[DRY-RUN] Would generate" if dry_run else "Generated"
    print(f"  {label}: _ctp_base.py (SWIG infrastructure with preserved imports)")


def generate_constants_module(
    constants_code: str, constant_names: list, output_dir: str, dry_run: bool = False
):
    """生成 ctp_constants.py — 包含所有 THOST_* 常量赋值语句。"""
    import_line = _determine_imports(constants_code, is_constants=True)
    all_list = ",\n".join(f'    "{n}"' for n in constant_names)

    content = (
        _AUTO_GEN_HEADER
        + f'"""{_MODULE_DESCRIPTIONS["ctp_constants"]}"""\n\n'
        + import_line
        + "\n\n"
        + constants_code
        + "\n__all__ = [\n"
        + all_list
        + ",\n]\n"
    )
    filepath = os.path.join(output_dir, "ctp_constants.py")
    _write_file(filepath, content, dry_run)
    label = "[DRY-RUN] Would generate" if dry_run else "Generated"
    print(f"  {label}: ctp_constants.py ({len(constant_names)} constants)")


def generate_class_module(
    module_name: str, class_names: list, class_blocks: dict, output_dir: str, dry_run: bool = False
):
    """生成一个类子模块 — 包含实际的类定义代码。"""
    # 合并该模块所有类的代码
    code_parts = []
    for name in class_names:
        code_parts.append(class_blocks[name])
    merged_code = "".join(code_parts)

    import_line = _determine_imports(merged_code)
    desc = _MODULE_DESCRIPTIONS.get(module_name, module_name)
    all_list = ",\n".join(f'    "{n}"' for n in class_names)

    content = (
        _AUTO_GEN_HEADER
        + f'"""{desc}"""\n\n'
        + import_line
        + "\n\n"
        + merged_code
        + "\n__all__ = [\n"
        + all_list
        + ",\n]\n"
    )
    filepath = os.path.join(output_dir, f"{module_name}.py")
    _write_file(filepath, content, dry_run)
    label = "[DRY-RUN] Would generate" if dry_run else "Generated"
    print(f"  {label}: {module_name}.py ({len(class_names)} classes)")


def generate_compat_ctp_py(module_names: list, output_dir: str, dry_run: bool = False):
    """用向后兼容垫片替换原始 ctp.py。

    新的 ctp.py 从 _ctp_base 和所有子模块重新导入全部符号，
    使得 ``from .ctp import *`` 的行为与原始文件完全一致。
    """
    lines = [
        _AUTO_GEN_HEADER,
        '"""',
        "CTP Python wrapper — 向后兼容垫片",
        "",
        "原始文件由 SWIG 自动生成，现已被 split_ctp_wrapper.py 拆分为子模块。",
        "本文件从各子模块重新导入全部符号，保持 ``from .ctp import *`` 的兼容性。",
        '"""',
        "",
        "from ._ctp_base import *  # noqa: F401,F403  — SWIG infrastructure",
    ]
    for mod in module_names:
        lines.append(f"from .{mod} import *  # noqa: F401,F403")
    lines.append("")

    content = "\n".join(lines)
    filepath = os.path.join(output_dir, "ctp.py")
    _write_file(filepath, content, dry_run)
    label = "[DRY-RUN] Would replace" if dry_run else "Replaced"
    print(f"  {label}: ctp.py (backward-compat shim)")


# ===================================================================
#  验证
# ===================================================================


def validate(constant_names, class_names, module_class_map):
    """验证: 无遗漏、无重复。"""
    all_classified = []
    for cls_list in module_class_map.values():
        all_classified.extend(cls_list)

    classified_set = set(all_classified)
    original_set = set(class_names)

    missing = original_set - classified_set
    duplicates = len(all_classified) - len(classified_set)

    ok = True
    if missing:
        print(f"  WARNING: {len(missing)} classes not classified: {missing}")
        ok = False
    if duplicates:
        print(f"  WARNING: {duplicates} duplicate classifications found")
        ok = False

    if ok:
        print(
            f"  Validation OK: {len(class_names)} classes, "
            f"{len(constant_names)} constants, no duplicates"
        )
    return ok


# ===================================================================
#  清理旧文件
# ===================================================================


def cleanup_old_files(output_dir):
    """删除之前自动生成的子模块文件。"""
    removed = []
    for mod_name in _ALL_GENERATED_FILES:
        filepath = os.path.join(output_dir, f"{mod_name}.py")
        if os.path.exists(filepath):
            with open(filepath, "r", encoding="utf-8") as f:
                first_line = f.readline()
            if _AUTO_GEN_HEADER.strip() in first_line:
                os.remove(filepath)
                removed.append(filepath)
    # ctp.py 兼容垫片
    ctp_py = os.path.join(output_dir, "ctp.py")
    if os.path.exists(ctp_py):
        with open(ctp_py, "r", encoding="utf-8") as f:
            first_line = f.readline()
        if _AUTO_GEN_HEADER.strip() in first_line:
            os.remove(ctp_py)
            removed.append(ctp_py)
    if removed:
        print(f"  Cleaned up {len(removed)} old auto-generated files")
    return removed


# ===================================================================
#  主入口
# ===================================================================


def split_ctp_wrapper(ctp_py_path=None, output_dir=None, dry_run=False):
    """执行拆分: 解析 ctp.py → 提取代码 → 生成子模块 → 替换 ctp.py。

    Args:
        ctp_py_path: ctp.py 的路径，默认为 bt_api_py/ctp/ctp.py
        output_dir: 输出目录，默认与 ctp.py 同目录
        dry_run: 如果 True，只打印不写文件

    Returns:
        bool: 是否成功
    """
    if ctp_py_path is None:
        ctp_py_path = _CTP_PY_PATH
    if output_dir is None:
        output_dir = os.path.dirname(ctp_py_path)

    if not os.path.exists(ctp_py_path):
        print(f"WARNING: {ctp_py_path} not found, skipping CTP wrapper split")
        return False

    # 如果 ctp.py 已经是兼容垫片，则跳过
    with open(ctp_py_path, "r", encoding="utf-8") as f:
        head = f.readline()
    if _AUTO_GEN_HEADER.strip() in head:
        print(f"CTP wrapper already split (ctp.py is compat shim), skipping")
        return True

    print(f"Splitting CTP wrapper: {ctp_py_path}")

    # 解析
    preamble_code, constants_code, class_blocks, constant_names, class_names = parse_ctp_py(
        ctp_py_path
    )
    print(f"  Parsed: {len(constant_names)} constants, {len(class_names)} classes")

    # 分类
    module_class_map = OrderedDict()  # module_name -> [class_names]
    for mod_name in _MODULE_DESCRIPTIONS:
        if mod_name != "ctp_constants":
            module_class_map[mod_name] = []

    for cls_name in class_names:
        mod = classify_class(cls_name)
        module_class_map[mod].append(cls_name)

    # 验证
    ok = validate(constant_names, class_names, module_class_map)
    if not ok:
        return False

    # 清理旧文件
    if not dry_run:
        cleanup_old_files(output_dir)

    # 生成 _ctp_base.py
    generate_base_module(preamble_code, output_dir, dry_run)

    # 生成 ctp_constants.py
    generate_constants_module(constants_code, constant_names, output_dir, dry_run)

    # 生成各类子模块
    for mod_name, cls_list in module_class_map.items():
        if cls_list:
            generate_class_module(mod_name, cls_list, class_blocks, output_dir, dry_run)

    # 替换 ctp.py 为兼容垫片
    active_modules = ["ctp_constants"] + [m for m, c in module_class_map.items() if c]
    generate_compat_ctp_py(active_modules, output_dir, dry_run)

    # 汇总
    total_classes = sum(len(c) for c in module_class_map.values())
    total_modules = sum(1 for c in module_class_map.values() if c) + 1  # +1 for constants
    print(
        f"  Total: {total_classes} classes + {len(constant_names)} constants "
        f"in {total_modules} modules + _ctp_base + ctp.py shim"
    )

    return ok


def main():
    import argparse

    parser = argparse.ArgumentParser(
        description="Split SWIG-generated ctp.py into sub-modules (v2: real code extraction)"
    )
    parser.add_argument("--ctp-py", default=None, help="Path to ctp.py")
    parser.add_argument("--output-dir", default=None, help="Output directory")
    parser.add_argument("--dry-run", action="store_true", help="Print plan without writing files")
    args = parser.parse_args()

    ok = split_ctp_wrapper(
        ctp_py_path=args.ctp_py,
        output_dir=args.output_dir,
        dry_run=args.dry_run,
    )
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
