id: btcturk
display_name: BTCTurk
venue_type: cex
website: https://www.btcturk.com
api_doc: https://docs.btcturk.com/
base_urls:
  rest:
    default: https://api.btcturk.com
    spot: https://api.btcturk.com
  wss:
    default: wss://ws-feed-pro.btcturk.com
    spot: wss://ws-feed-pro.btcturk.com
authentication:
  type: hmac_sha256
  header_name: X-PCK
kline_periods:
  1m: '1'
  5m: '5'
  15m: '15'
  30m: '30'
  1h: '60'
  4h: '240'
  1d: '1440'
  1w: '10080'
legal_currency: &id001
- USDT
- TRY
- BTC
- ETH
- USDC
rate_limits:
- name: public_api
  type: sliding_window
  interval: 60
  limit: 1200
  scope: global
- name: private_api
  type: sliding_window
  interval: 60
  limit: 600
  scope: global
- name: websocket
  type: sliding_window
  interval: 60
  limit: 15
  scope: global
asset_types:
  spot:
    exchange_name: btcturkSpot
    rest_paths:
      get_server_time: GET /api/v2/server/time
      get_ticker: GET /api/v2/ticker
      get_depth: GET /api/v2/orderbook
      get_kline: GET /api/v2/ohlcs
      get_exchange_info: GET /api/v2/server/exchangeinfo
      get_trades: GET /api/v2/trades
    wss_paths:
      ticker: ticker
      orderbook: orderbook
      trade: trade
    symbol_format: '{base}/{quote}'
    legal_currency: *id001
connection:
  type: http
  timeout: 10
  max_retries: 3
