id: cow_swap
display_name: CoW Swap
venue_type: dex
website: https://cow.fi
api_doc: https://docs.cow.fi/
base_urls:
  rest:
    default: https://api.cow.fi
    spot: https://api.cow.fi
  wss:
    default: ''
    spot: ''
authentication:
  type: none
  header_name: ''
kline_periods:
  1m: '60'
  5m: '300'
  15m: '900'
  30m: '1800'
  1h: '3600'
  4h: '14400'
  1d: '86400'
legal_currency: &id001
- USDT
- USD
- EUR
- DAI
- USDC
- BTC
- ETH
- WETH
rate_limits:
- name: public_api
  type: sliding_window
  interval: 60
  limit: 300
  scope: global
supported_chains:
- name: mainnet
  chain_id: 1
  rest_path: /mainnet
- name: xdai
  chain_id: 100
  rest_path: /xdai
- name: arbitrum_one
  chain_id: 42161
  rest_path: /arbitrum_one
- name: base
  chain_id: 8453
  rest_path: /base
- name: avalanche
  chain_id: 43114
  rest_path: /avalanche
- name: polygon
  chain_id: 137
  rest_path: /polygon
asset_types:
  spot:
    exchange_name: cow_swapSpot
    rest_paths:
      get_orders: GET /api/v1/orders
      get_order: GET /api/v1/orders/{uid}
      get_order_status: GET /api/v1/orders/{uid}/status
      get_account_orders: GET /api/v1/account/{owner}/orders
      get_trades: GET /api/v2/trades
      get_transaction_orders: GET /api/v1/transactions/{txHash}/orders
      get_solver_competition: GET /api/v2/solver_competition/{auction_id}
      get_solver_competition_latest: GET /api/v2/solver_competition/latest
      get_token_price: GET /api/v1/token/{token}/native_price
      get_version: GET /api/v1/version
    wss_paths: {}
    symbol_format: '{base}/{quote}'
    legal_currency: *id001
connection:
  type: http
  timeout: 10
  max_retries: 3
