id: luno
display_name: Luno
venue_type: cex
website: https://www.luno.com
api_doc: https://www.luno.com/en/api
base_urls:
  rest:
    default: https://api.luno.com/api/1
    spot: https://api.luno.com/api/1
  rest_exchange: https://api.luno.com/api/exchange/1
  wss:
    default: wss://api.luno.com/api/1
    spot: wss://api.luno.com/api/1
authentication:
  type: api_key
  header_name: Authorization
kline_periods:
  1m: '60'
  5m: '300'
  15m: '900'
  30m: '1800'
  1h: '3600'
  3h: '10800'
  4h: '14400'
  1d: '86400'
  3d: '259200'
  1w: '604800'
legal_currency: &id001
- ZAR
- NGN
- MYR
- IDR
- EUR
- GBP
- UGX
- AUD
- ZMW
rate_limits:
- name: public_api
  type: sliding_window
  interval: 60
  limit: 300
  scope: global
- name: private_api
  type: sliding_window
  interval: 60
  limit: 300
  scope: global
asset_types:
  spot:
    exchange_name: LUNO___SPOT
    rest_paths:
      get_server_time: GET /api/1/time
      get_ticker: GET /api/1/ticker
      get_tickers: GET /api/1/tickers
      get_depth: GET /api/1/orderbook
      get_depth_top: GET /api/1/orderbook_top
      get_trades: GET /api/1/trades
      get_kline: GET /api/exchange/1/candles
      get_markets: GET /api/exchange/1/markets
    symbol_format: '{base}/{quote}'
    legal_currency: *id001
connection:
  type: http
  timeout: 10
  max_retries: 3
