id: mercado_bitcoin
display_name: Mercado Bitcoin
venue_type: cex
website: https://www.mercadobitcoin.com.br
api_doc: https://www.mercadobitcoin.com.br/api-doc
base_urls:
  rest:
    default: https://www.mercadobitcoin.net/api
    spot: https://www.mercadobitcoin.net/api
  rest_private: https://www.mercadobitcoin.net/tapi
  rest_v4: https://api.mercadobitcoin.net/api/v4
  wss:
    default: wss://ws.mercadobitcoin.net
    spot: wss://ws.mercadobitcoin.net
authentication:
  type: hmac_sha512
  header_name: TAPI-MAC
kline_periods:
  15m: 15m
  1h: 1h
  3h: 3h
  1d: 1d
  1w: 1w
  1M: 1M
legal_currency: &id001
- BRL
rate_limits:
- name: public_api
  type: sliding_window
  interval: 1
  limit: 1
  scope: global
- name: private_api
  type: sliding_window
  interval: 1
  limit: 1
  scope: global
asset_types:
  spot:
    exchange_name: MERCADO_BITCOIN___SPOT
    rest_paths:
      get_server_time: GET /api/BTC/ticker/
      get_ticker: GET /{coin}/ticker/
      get_depth: GET /{coin}/orderbook/
      get_trades: GET /{coin}/trades/
      get_kline: GET /api/v4/candles
      get_coins: GET /coins
    symbol_format: '{base}/{quote}'
    legal_currency: *id001
connection:
  type: http
  timeout: 10
  max_retries: 3
